### ISSUE TITLE
How to set visualization parameter according to quaternion

### ISSUE THREAD

**Issue by aditdoshi333** [isl-org/Open3D#4208] opened 2021-10-28 07:23 UTC
Hello,
I am using open3d visualiser for mesh. I am having robot's trajectory from ROS, It contains x, y, z as position and quaternion for orientation. Now I want to move the camera in way that it travel along the trajectory. 

I am not able to understand how to set front lookup and up vector. I thought of translating camera to the position but viewControl translate is taking just x and y. 

Any help is appreciated. Thank you

**Comment by howz-chen** [comment] 2022-05-17 08:17
I have same question like this. For example, I want to visualize the cloudpoint data which taken by lidar on the car with the first-person view, but now I'm confused about the up/front vector args on python API (open3d.visualization.Visualizer().get_view_control().set_up()), if I have odometry info which contains pos x/y/z and quaternion x/y/z/w, how can I to calc the up/front vector?

**Comment by yuecideng** [comment] 2022-05-17 08:43
You can convert your `xyz` and `quaternion` into a 4x4 transformation matrix, and assign it to the extrinsic of `open3d.camera.PinholeCameraParameters`. Then you can use `convert_from_pinhole_camera_parameters` API which takes camera param as input to adjust the control of view.

**Comment by howz-chen** [comment] 2022-05-18 07:51
First of all, I'm very apprciate your reply @yuecideng .
I have realize method in your suggestion, the code like below.

**The main step of my code**:
1. read the whole pcd file and read odometry file, create window and get view control.
2. use open3d.camera.PinholeCameraParameters() to get default parameters of camera, which include intrinsic and extrinsic, we call it cam_param.
3. use pos x/y/z and quaternion(x/y/z/w) to create 4x4 transformation matrix, and assign it to  replace default cam_param.extrinsic.
4. use convert_from_pinhole_camera_parameters(param) to adjust the control of view.
5. show the pcd and update visualization result with the change of camera pose frame by frame.


Other attempts:
1. if I not set intrinsic, the window only show a small color grid, I guess this caused by default width/height which is -1.
2. when I use convert_from_pinhole_camera_parameters API, if arg allow_arbitrary is false, I would see the whole pcd with bird eye view; while set the allow_arbitrary with true, the view is strange.

I hope that after setting up, I can achieve first-person driving view to see the detail of point around, while running this code, I got the strange view. The purpose of pasting the code is to make sure that my steps are not wrong. So, if you have time, pls see my code and I'm looking forward to your reply, thanks again!

**Please forgive me for not uploading data and screenshots due to data sensitivity issues.**

```
import open3d as o3d
import numpy as np
from scipy.spatial.transform import Rotation as R
import csv
import os

def load_view_point(pcd, intrinsic, csv_content):
    vis = o3d.visualization.Visualizer()
    vis.create_window(window_name='pcd', width=1200, height=800)
    vis.add_geometry(pcd)

    ctr = vis.get_view_control()
    # get default camera parameters
    param = o3d.camera.PinholeCameraParameters()
    param.intrinsic.intrinsic_matrix = intrinsic
    # get the pos x/y/z and quaternion frame by frame
    for i in range(len(csv_content)):
        temp_data = csv_content[i]
        temp_data = list(map(float, temp_data))
        # get quaternion  [x,y,z,w]
        Rq = [temp_data[1], temp_data[2], temp_data[3], temp_data[4]]
        # get position [x,y,z]
        t = np.array(temp_data[5:])
        # create 4x4 transformation matrix
        extrinsic_matrix = np.eye(4)
        rotation_matrix = R.from_quat(Rq).as_matrix()
        extrinsic_matrix[:3, :3] = rotation_matrix
        extrinsic_matrix[:3, 3] = t.T
        param.extrinsic = extrinsic_matrix

        # set param to current camera control view
        ctr.convert_from_pinhole_camera_parameters(param, allow_arbitrary=True)
        vis.update_geometry(pcd)
        vis.poll_events()
        vis.update_renderer()
    vis.destroy_window()

if __name__ == "__main__":
    cur_dir = os.path.dirname(os.path.abspath(__file__))
    csv_reader = csv.reader(open(os.path.join(cur_dir, "key_frame_odometry.txt")))

    csv_content = []
    for line in csv_reader:
        csv_content.append(line)

    pcd = o3d.io.read_point_cloud(os.path.join(cur_dir, "example.pcd"))
    points = np.asarray(pcd.points)
    # save_view_point(pcd, "viewpoint.json")
    intrinsic = np.array([[1037.536376953125, 0, 599.5],
                 [0, 1038.532958984375, 399.5],
                 [0, 0, 1]])

    load_view_point(pcd, intrinsic, csv_content)
```

**Comment by yuecideng** [comment] 2022-05-18 09:32
My suggestion would be just based on my personal imagination... (I am lack of experience with lidar data)

You should find a way to determine the "transformation offset" from your lidar data coordinate to your view point coordinate (may be do this in `cloudcompare` using your first frame data) . The view point is located at the center of your lidar data and with z axis point to the view direction you are interested. Then apply this "offset" to the odometry you want to visualize.
I think your work flow is no problem. Just use a suitable camera intrinsic based human eye fov. [fov to intrinsic](https://codeyarns.com/tech/2015-09-08-how-to-compute-intrinsic-camera-matrix-for-a-camera.html)

**Comment by howz-chen** [comment] 2022-05-18 09:37
@yuecideng  Thanks for your suggestion. I will try it again and update my progress here later.

**Comment by howz-chen** [comment] 2022-06-07 08:27
I realize this function by setting front/up vector.  

The problem main appear at 
1. order of elements in quaternion, I used to set quaternion with [ox, oy, oz, ow] while the right order is [ow, ox, oy, oz]
2. use "o3d.geometry.get_rotation_matrix_from_quaternion(YOUR_QUATERNION)"  function to get ROTATION_MATRIX, and first/third column represent front/up  vector seperately.

Then, set
view_control = o3d.visualization.Visualizer().get_view_control()
view_control.set_front(front_vector)
view_control.set_up(up_vector)
view_control.set_lookat($YOUR_CAMERA_POSITION$)    # camera_pos in global coordinate system
view_control.set_zoom(0.01)

At last, update your point cloud recursively, and I can realize navigation at the first-persion view.

This [CSDN blog post](https://blog.csdn.net/IT_forlearn/article/details/125056069?spm=1001.2014.3001.5501) show simple realization of this function.

Sorry for the late update and thanks for previous suggestion again @yuecideng

**Closed** 2022-06-22 11:09 UTC
Labels: visualization, viewcontrol
