### ISSUE TITLE
Reconstruction Pipeline on custom data error 'no correspondences between source and target point cloud'

### ISSUE THREAD

**Issue by nikhilgiji** [isl-org/Open3D#4337] opened 2021-11-23 15:48 UTC
Open3D reconstruction pipeline is showing error when using custom data.

- ColoredICP.cpp:124: No correspondences found between source and target pointcloud. 

The reconstruction pipeline is generating fragments, but it is not able to combine the fragments, I have also used the camera intrinsic matrix.

**Comment by theNded** [comment] 2021-11-23 16:28
Could you please provide more context? How does the source and target look like, and have you performed global registration before that?

**Comment by nikhilgiji** [comment] 2021-11-24 04:36
I have extracted 994 frames and their corresponding 16bit depth map of teeth data, and I have run the reconstruction pipeline and it has generated 10 fragments but it is not able to combine the fragments and generate the scene. I have run the pipeline using:

'python3 run_system.py tutorial.json --make --register --refine --integrate' 

it is showing the error:

`[Open3D Error] (class Eigen::Matrix<double,4,4,0,4,4> __cdecl open3d::pipelines::registration::TransformationEstimationForColoredICP::ComputeTransformation(const class open3d::geometry::PointCloud &,const class open3d::geometry::PointCloud &,const class std::vector<class Eigen::Matrix<int,2,1,0,2,1>,class std::allocator<class Eigen::Matrix<int,2,1,0,2,1> > > &) const) D:\a\Open3D\Open3D\cpp\open3d\pipelines\registration\ColoredICP.cpp:124: No correspondences found between source and target pointcloud.

Traceback (most recent call last):
  File "run_system.py", line 123, in <module>
    refine_registration.run(config)
  File "D:\cs\Python\Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 228, in run
    make_posegraph_for_refined_scene(ply_file_names, config)
  File "D:\cs\Python\Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 204, in make_posegraph_for_refined_scene
    register_point_cloud_pair(ply_file_names,
  File "D:\cs\Python\Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 151, in register_point_cloud_pair
    local_refinement(source, target, transformation_init, config)
  File "D:\cs\Python\Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 132, in local_refinement
    multiscale_icp(
  File "D:\cs\Python\Open3D-master\Open3D-master\examples\python\reconstruction_system\refine_registration.py", line 101, in multiscale_icp`

**Comment by theNded** [comment] 2021-11-27 20:23
Duplicate of #4346.

**Closed by theNded** 2021-11-27 20:23 UTC
Labels: reconstruction, registration
