### ISSUE TITLE
open3d.visualization crashing Python interpreter

### ISSUE THREAD

**Issue by noahstier** [isl-org/Open3D#1715] opened 2020-04-16 17:55 UTC
**Description**

Creating a matplotlib window after using o3d.visualization.draw_geometries crashes the Python interpreter with the following error message:
```
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  15 (X_QueryTree)
Resourc eid in failed request:  0x3e000a7
Serial number of failed request:  1360
Current serial number in output stream:  1360
```

**To Reproduce**
1. open the o3d visualization window
2. close it
3. open a matplotlib window
4. close it
```
import open3d as o3d
import matplotlib.pyplot as plt

pc = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(np.random.rand(2, 3)))
o3d.visualization.draw_geometries([pc]) # close it
fig = plt.figure() # close it
```

**Environment**
Ubuntu 18.04
Python 3.7.6
Open3D 0.9.0.0
Not a remote workstation
Installed Open3D with pip

**Additional Information**
My interpreter crashes all the time a few statements after using open3d.visualization. This is just the one example I've found that does it consistently.

**Comment by ManuelZ** [comment] 2020-04-26 05:04
I can also confirm this, just happened to me. Same environment as the described above.

**Comment by pvarvak** [comment] 2020-04-29 03:12
I am having a problem reproducing this, whether I install open3d via pip or compile master branch.  Can you follow along the commands I did for pip install:
https://gist.github.com/pvarvak/34e813af82c4660bc8b914d33338c7f3
and for compiling master branch:
https://gist.github.com/pvarvak/a95b01e761874d8156fe4e7f012b3205
and put up gist with what your output was?
(If you run into compilation issues, please check https://github.com/intel-isl/Open3D/blob/master/docs/compilation.rst that appropriate dependencies have been installed, including virtualenv and python-pip)

**Comment by noahstier** [comment] 2020-04-29 19:55
I figured out a fix, at least for my situation.

Background: I use `ipython --pylab tk` primarily as my interactive interpreter. This conveniently imports numpy and matplotlib, and sets matpotlib to interactive mode, but it also does some other stuff, I'm not sure what exactly.

I discovered that I don't get the crashing bug if I don't use the `--pylab tk` option. According to [this thread](https://stackoverflow.com/questions/20525459/ipython-pylab-vs-ipython), using `pylab` is not recommended anyway.

So as a workaround / improvement to my current setup, I changed my ipython alias to `ipython --matplotlib` to get automatic interactive mode, and I copied pylab's imports into  `~/.ipython/profile_default/startup/imports.ipy`:
```
    import numpy
    import matplotlib
    from matplotlib import pylab, mlab, pyplot
    np = numpy
    plt = pyplot

    from IPython.display import display
    from IPython.core.pylabtools import figsize, getfigs

    from pylab import *
    from numpy import *
```

Now I don't get the crashing bug any more.

**Comment by noahstier** [comment] 2020-04-29 21:35
Gah I just got another crash even with the changes I described above... If I can find another way to consistently reproduce the crash I'll post it.

**Comment by SebastianGrans** [comment] 2020-05-27 06:35
I have also stumbled into this problem. 
For me it was caused by performing it in the opposite order. I.e. matplotlib followed by o3d.

**Comment by maggielovedd** [comment] 2020-09-26 02:38
Same problem, I've tried both way (matplotlib followed by o3d and inverse) and both pop out the error. I'm also using open3d 0.9 by pip install. System: Ubuntu16.04

**Comment by derEskimo** [comment] 2020-10-01 14:38
Sorry, can't help, but I get this Error too:(

In my application i have a while loop showing something in Open3d then poping up a tkinter dialog.
It is running for two iterations then always crahes with the given X Error above.

I have also noticed that when I want to use matplotlib after a visualization by Open3d the error appears too.
Guess because it builds on tkinter.

My System is running Ubuntu16.04 with open3d 0.9 installed via pip.
Anyone knows a fix? I would realy appreciate it.

**Comment by Sterris** [comment] 2020-12-02 13:53
Same thing happening to me. 
Tried installing open3d via pip and conda and used different versions of python, crashes every time.

**Comment by harishkashyap** [comment] 2020-12-22 00:09
same here

**Comment by hernot** [comment] 2021-03-03 12:05
same here when running visualizer in non blocking mode and trying to halt at a break point in python postmortem debugger from command line (python3 -mpdb myo3dvisualizerscirpt.py . As soon as postmortem debugger swiches X window to interactive mode visualizers crashes with bad window as if it tries to render to commandline window instead of its own viewer window. Assumingly it does for sake of speed not check if the window it tries to draw to or manipulate is still the active window in the the main thread. Strangely when switching focus to openCV.imshow window  crash does not happen. Just when some console input from interactive python command line is to be expected.

**Comment by szx0112** [comment] 2021-09-22 20:46
Same condition. I am trying to show the images (using either plt.show or cv2.imshow()) along draw_geoemtry. The open3d window crashes every time.

**Comment by hernot** [comment] 2021-09-24 07:01
I meanwhile switched to `visualization.O3DVisualizer` with running the gui thread in back ground. And sending all draw commands via `visualization.O3DVisualizer.send_to_main thread` to the background thread. The only issue is when finishing python or trying to restart in debugger that for now a core dump is generated which could easily be solved when there would exists a reset function as oposit to initialize to fully deinitialize and reset gui system as reported in feature requrest #3914.

**Comment by germanros1987** [comment] 2021-12-03 06:51
Is this still an issue in the newest version of Open3d using the new visualization API?

**Comment by hernot** [comment] 2021-12-03 12:57
Even though, see above, not using old visualization any more, I guess if all visualization.draw_functions and viewers use in the background the new filament based GUI it may be assumed that this is not an issue any more. In some of them still use home brew GL code than this issue still stays.

**Comment by mli0603** [comment] 2021-12-13 16:15
Similar issue here as @hernot describted above.

Environment:
Ubuntu 18.04
Python 3.8
Open3D 0.13
Not a remote workstation
Installed Open3D with pip

- Window crashes with `X Error of failed request:  BadWindow (invalid Window parameter)` when trying to set a breakpoint.
- `O3DVisualizer` works, and thus all `draw` commands work.
- `visualizer` crashes

**Comment by domef** [comment] 2022-09-26 07:21
I have the same problem

**Comment by domef** [comment] 2022-12-09 16:30
any update?

**Comment by hernot** [comment] 2022-12-10 09:02
@domef and all others I my self have switched more to new gui nearly two years ago to avoid this issue. Did you test using the latest open3Dversion. And third I guess the open3D team  is concentrating upon new gui, which as i have the impression will under the hood sooner or later replace the old visualization.
Therefore i do suggest in case you need it timely, do not want to use the new viewer and not invest the time to build your own gui, the best option you have in this case is to open a new issue requesting that rebasing visualization function upon new GUI is given a lot higher priority be the open3D team than receives up to now.

**Comment by ssheorey** [comment] 2023-03-13 02:02
This should be resolved in master (and in v0.17). I cannot reproduce the crash. (macOS or Ubuntu 22.04).

**Closed by ssheorey** 2023-03-13 02:02 UTC
Labels: possible bug, visualization, legacy (Open3D 0.x API)

**Comment by domef** [comment] 2023-03-13 04:49
> @domef and all others I my self have switched more to new gui nearly two years ago to avoid this issue. Did you test using the latest open3Dversion. And third I guess the open3D team is concentrating upon new gui, which as i have the impression will under the hood sooner or later replace the old visualization. Therefore i do suggest in case you need it timely, do not want to use the new viewer and not invest the time to build your own gui, the best option you have in this case is to open a new issue requesting that rebasing visualization function upon new GUI is given a lot higher priority be the open3D team than receives up to now.

How can I use the new GUI?

**Comment by coutyou** [comment] 2024-02-19 11:37
Similar problem:
```python
import open3d as o3d
from matplotlib import pyplot as plt

for _ in range(2):
    vis = o3d.visualization.Visualizer()
    vis.create_window(visible=False)
    vis.destroy_window()
    plt.figure()
    plt.close()
```
will get error:
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x1800020
  Serial number of failed request:  459
  Current serial number in output stream:  459
```
However, this code is fine:
```python
import open3d as o3d
from matplotlib import pyplot as plt

for _ in range(1):
    vis = o3d.visualization.Visualizer()
    vis.create_window(visible=False)
    vis.destroy_window()
    plt.figure()
    plt.close()
```
Also, the example code is fine:
```python
import open3d as o3d
import matplotlib.pyplot as plt
import numpy as np

pc = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(np.random.rand(2, 3)))
o3d.visualization.draw_geometries([pc]) # close it
fig = plt.figure() # close it
```
Environment
Ubuntu 18.04.6 LTS
Python 3.8.17
Open3D 0.18.0
A remote workstation connected by VNCViewer
Installed Open3D with pip

**Comment by hernot** [comment] 2024-02-19 17:02
@coutyou did you check which backend matplotlib is using or did you try to explicitly set gtk_agg, qt_agg or any of the other non tk backends for matplotlib. Cause it is tkinter which assumes that it is the one and only gui framework in the process. As soon as another one is added like the O3DViewer and alike than the whole will crash. Luckily matplotlib supports more modern frameworks which switch drawing context first before drawing and integrate better with opengl frameworks like filament (used by open3d) than ktinter does.

**Comment by coutyou** [comment] 2024-02-20 06:04
> @coutyou did you check which backend matplotlib is using or did you try to explicitly set gtk_agg, qt_agg or any of the other non tk backends for matplotlib. Cause it is tkinter which assumes that it is the one and only gui framework in the process. As soon as another one is added like the O3DViewer and alike than the whole will crash. Luckily matplotlib supports more modern frameworks which switch drawing context first before drawing and integrate better with opengl frameworks like filament (used by open3d) than ktinter does.

After switching to a non tk backend, the code can run smoothly. Many thanks!
```python
import open3d as o3d
from matplotlib import pyplot as plt
import matplotlib

# TkAgg
print(matplotlib.get_backend())
matplotlib.use('agg')
# agg
print(matplotlib.get_backend())

for _ in range(2):
    vis = o3d.visualization.Visualizer()
    vis.create_window(visible=False)
    vis.destroy_window()
    plt.figure()
    plt.close()
```

**Comment by domef** [comment] 2024-10-01 13:09
With `Agg` backend i get `UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown`.

**Comment by hernot** [comment] 2024-10-01 15:02
> With `Agg` backend i get `UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown`.

Use gtk*_agg or qt_agg instead
