### ISSUE TITLE
The parameter documentation for o3d.geometry.TriangleMesh.scale() has duplicates

### ISSUE THREAD

**Issue by benjaminum** [isl-org/Open3D#2220] opened 2020-08-23 18:31 UTC
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**
The parameter documentation for o3d.geometry.TriangleMesh.scale() has duplicates.

**Expected behavior**
Doc with actual signature

**Environment (please complete the following information):**

- Open3D version: master

**Comment by griegler** [comment] 2020-08-23 18:35
Also `rotate`.
@yxlao I guess this is caused by how overloaded methods are handled?

**Comment by ssheorey** [comment] 2021-12-03 00:42
Fixed by PR #3373

**Closed by ssheorey** 2021-12-03 00:42 UTC
Labels: docs, bug
