### ISSUE TITLE
Failed import on 0.16.0 on OSX M1 after pip install?

### ISSUE THREAD

**Issue by nickponline** [isl-org/Open3D#5655] opened 2022-11-05 21:36 UTC
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Steps to reproduce the issue

```
pip3 install open3d==0.16.0
python3
import open3d
```

### Error message

```shell
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nickp/opt/anaconda3/envs/dev/lib/python3.7/site-packages/open3d/__init__.py", line 97, in <module>
    from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: dlopen(/Users/nickp/opt/anaconda3/envs/dev/lib/python3.7/site-packages/open3d/cpu/pybind.cpython-37m-darwin.so, 0x0002): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
  Referenced from: '/Users/nickp/opt/anaconda3/envs/dev/lib/python3.7/site-packages/open3d/cpu/pybind.cpython-37m-darwin.so'
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)
>>> 
```
```


### Open3D, Python and System information

```markdown
- Operating system: Mac M1 OSX 12.6
- Python version: Python 3.7.12 | packaged by conda-forge | [Clang 11.1.0 ] on darwin
- Open3D version: 0.16.0
- System architecture: Darwin m1 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

### Additional information

I've tried `brew install libomp` which yields:

```
==> Pouring libomp--15.0.4.arm64_monterey.bottle.tar.gz
==> Caveats
libomp is keg-only, which means it was not symlinked into /opt/homebrew,
because it can override GCC headers and result in broken builds.

For compilers to find libomp you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"

==> Summary
🍺  /opt/homebrew/Cellar/libomp/15.0.4: 7 files, 1.6MB
==> Running `brew cleanup libomp`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/libomp/15.0.3... (7 files, 1.6MB)
Removing: /Users/nickp/Library/Caches/Homebrew/libomp--15.0.3... (543.0KB)
```

If I then symlink /opt/homebrew/opt/libomp /usr/local/opt/. The error is:

```
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nickp/opt/anaconda3/envs/dev/lib/python3.7/site-packages/open3d/__init__.py", line 97, in <module>
    from open3d.cpu.pybind import (camera, data, geometry, io, pipelines,
ImportError: dlopen(/Users/nickp/opt/anaconda3/envs/dev/lib/python3.7/site-packages/open3d/cpu/pybind.cpython-37m-darwin.so, 0x0002): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
  Referenced from: '/Users/nickp/opt/anaconda3/envs/dev/lib/python3.7/site-packages/open3d/cpu/pybind.cpython-37m-darwin.so'
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)
```

**Comment by nickponline** [comment] 2022-11-08 21:05
@yxlao do you know what the solution to this is?

**Comment by jbotsch-fy** [comment] 2022-11-09 08:34
might be related to https://github.com/isl-org/Open3D/issues/5607 ?

@yxlao, @ssheorey: As a reminder, the 0.16 wheels for Mac Arm are currently broken and unusable.

**Comment by johnthagen** [comment] 2022-11-11 21:05
It looks like 0.16.1 was released with only Mac ARM wheels which might help with this:

- https://pypi.org/project/open3d/0.16.1/#files

**Comment by ssheorey** [comment] 2022-11-15 08:12
@nickponline please try the v0.16.1 wheels.

**Comment by PeggyYuchunWang** [comment] 2023-01-25 20:25
Hi! I'm getting the same error on python 3.10 on M1 Mac Pro after doing `brew install libomp`

I'm on Mac OS 12.6.1

```
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d
zsh: segmentation fault  python
```

**Comment by ssheorey** [comment] 2023-01-29 19:23
Closing since the original issue is confirmed resolved. @PeggyYuchunWang please try with a clean environment, if you still have a seg fault, please open a new issue.

**Closed by ssheorey** 2023-01-29 19:23 UTC
Labels: build/install issue
