### ISSUE TITLE
BUILD_SHARED_LIBS=ON compile error and linker error in C++/CLR project

### ISSUE THREAD

**Issue by cjwiles** [isl-org/Open3D#3589] opened 2021-06-15 20:17 UTC
Description:
1. Build of Open3d.lib fails when using BUILD_SHARED_LIBS=ON due to linker error on webrtc.lib
2. Link of Open3d.lib in C++/CLR project fails after successful compilation with BUILD_SHARED_LIBS=ON and BUILD_WEBRTC=OFF.

Recreating behavior in Description 1 (latest master, BUILD_SHARED_LIBS=ON):
checkout HEAD of master 7e813a89dd96364a753e313dba33c6d50419ab11
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:\open3d_install ..
cmake --build . --config Release --parallel 12 --target install
DOES NOT COMPILE
Many errors similar to:
webrtc.lib(decision_logic.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn'
t match value 'MD_DynamicRelease' in Open3DConfig.obj [D:\Repositories\Open3D_top\Open3D\build\cpp\open3d\Open3D.vcxpro
j]
Many errors similar to:
libcpmt.lib(xlocale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't matc
h value 'MD_DynamicRelease' in Open3DConfig.obj [D:\Repositories\Open3D_top\Open3D\build\cpp\open3d\Open3D.vcxproj]

Recreating behavior in Description 2 (latest master, BUILD_SHARED_LIBS=ON, BUILD_WEBRTC=OFF):
checkout HEAD of master
cmake -DBUILD_SHARED_LIBS=ON -DBUILD_WEBRTC=OFF -DCMAKE_INSTALL_PREFIX=C:\open3d_install ..
cmake --build . --config Release --parallel 12 --target install
Add Open3d.lib to C++/CLR project in VisualStudio 2019

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"public: __cdecl std::bad_array_new_length::bad_array_new_length(class std::bad_array_new_length const &)" (??0bad_array_new_length@std@@QEAA@AEBV01@@Z) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK2005	"public: __cdecl std::bad_alloc::bad_alloc(class std::bad_alloc const &)" (??0bad_alloc@std@@QEAA@AEBV01@@Z) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK2005	"public: __cdecl std::exception::exception(class std::exception const &)" (??0exception@std@@QEAA@AEBV01@@Z) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK2005	"public: virtual __cdecl std::bad_array_new_length::~bad_array_new_length(void)" (??1bad_array_new_length@std@@UEAA@XZ) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK2005	"public: virtual char const * __cdecl std::exception::what(void)const " (?what@exception@std@@UEBAPEBDXZ) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK1169	one or more multiply defined symbols found	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\x64\Release\ClassLibrary2.dll	1	

- Operating system: Windows 10 64-bit
- Python version: Python 3.6
- Open3D version: latest master, errors also when using 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: (build from source)
- Compiler version: The C compiler identification is MSVC 19.29.30037.0

**Additional context**
Also attempted to recreate the solution in #2889 using 0.12.0
- setting BUILD_SHARED_LIBS=OFF and STATIC_WINDOWS_RUNTIME=OFF failed to link in C++/CLR due to Many LNK2019 unresolved external symbol
- setting BUILD_SHARED_LIBS=ON and STATIC_WINDOWS_RUNTIME=OFF failed with
- Error	LNK2005	"public: __cdecl std::exception::exception(class std::exception const &)" (??0exception@std@@QEAA@AEBV01@@Z) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK2005	"public: __cdecl std::bad_alloc::bad_alloc(class std::bad_alloc const &)" (??0bad_alloc@std@@QEAA@AEBV01@@Z) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK2005	"public: __cdecl std::bad_array_new_length::bad_array_new_length(class std::bad_array_new_length const &)" (??0bad_array_new_length@std@@QEAA@AEBV01@@Z) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK2005	"public: virtual __cdecl std::bad_array_new_length::~bad_array_new_length(void)" (??1bad_array_new_length@std@@UEAA@XZ) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK2005	"public: virtual char const * __cdecl std::exception::what(void)const " (?what@exception@std@@UEBAPEBDXZ) already defined in Open3D.lib(Open3D.dll)	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\ClassLibrary2\MSVCRT.lib(throw_bad_alloc.obj)	1	
Error	LNK1169	one or more multiply defined symbols found	ClassLibrary2	D:\Repositories\578\Technical\RepoBackup\Walker578\x64\Release\ClassLibrary2.dll	1

**Comment by ssheorey** [comment] 2021-06-16 04:39
1. This configuration is not supported (BUILD_SHARED_LIBS=ON and BUILD_WEBRTC=ON) for MSVC, since we do not provide prebuilt binaries for WebRTC in this case. Please turn off WebRTC if you want shared libraries. Alternately, you can build webrtc from source as a shared library.

Duplicate of #3503 

2. Sorry, no idea about this since we don't test with C++/CLR. Does a plain C++ build work for you with BUILD_SHARED_LIBS=ON BUILD_WEBRTC=OFF and STATIC_WINDOWS_RUNTIME=OFF?

**Comment by cjwiles** [comment] 2021-06-16 16:26
To test a plain C++ build, I followed the instructions at https://github.com/intel-isl/open3d-cmake-find-package
With the following compile error:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: The command "setlocal [D:\Repositories\Open3D_top\Open3D_example\open3d-cmake-find-package\build\Draw.vcxproj]

**Comment by cjwiles** [comment] 2021-06-16 17:36
After copying my Open3D.dll to C:/Program Files (x86)/Open3DCMakeFindPackage/bin, I was able to compile the sample program

**Comment by ssheorey** [comment] 2021-06-16 17:46
@cjwiles this may be a permission error since you are trying to install to `C:/Program Files (x86)/`. Installing to a folder in your home directory should work.

Do let us know if you figure out the C++/CLR build.

**Closed** 2022-01-06 22:08 UTC
Labels: build/install issue, windows

**Comment by likehuaer** [comment] 2024-01-11 11:36
@cjwiles I see this issue has been closed.  Do you have fixed this problem? I also encountered the same problem:

1>  正在生成代码...
1>  .NETFramework,Version=v4.5.2.AssemblyAttributes.cpp
1>MSVCRT.lib(throw_bad_alloc.obj) : error LNK2005: "public: virtual char const * __cdecl std::exception::what(void)const " (?what@exception@std@@UEBAPEBDXZ) 已经在 Open3D.lib(Open3D.dll) 中定义
1>E:\VisionSharpDll-master\x64\Release\VisionSharpDll.dll : fatal error LNK1169: 找到一个或多个多重定义的符号
