### ISSUE TITLE
Direct fast interface for conversion from OpenCV Mat to Open3D Image

### ISSUE THREAD

**Issue by belalhmedan90** [isl-org/Open3D#6600] opened 2024-01-12 10:14 UTC
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Proposed new feature or change

To provide a direct interface for converting images from `CV::Mat` to `open3d::geometry::Image`

**Comment by ssheorey** [comment] 2024-01-12 23:17
Duplicate of #2645 

PS: this converts to the tensor based image, not the Eigen based image data type.

**Closed by ssheorey** 2024-01-12 23:17 UTC
Labels: feature request
