### ISSUE TITLE
Cannot Compile with Clang on RHEL 7.7

### ISSUE THREAD

**Issue by wctaylor** [isl-org/Open3D#4912] opened 2022-03-22 21:05 UTC
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

#### I first cloned Open3D by:
```
git clone https://github.com/isl-org/Open3D.git
cd Open3D
```

#### I create a `conda` environment to obtain the necessary dependencies and set the paths. 
```
conda create -n test
conda activate test
conda install python pip
conda install -c conda-forge cmake clang c-compiler cxx-compiler git libcxx libcxxabi libglu mesalib xorg-libxcursor xorg-libxi xorg-libxinerama xorg-libxrandr yasm
```

#### Then, I build Open3D (on RHEL 7.7) with:
```
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang -DBUILD_GUI=ON -DBUILD_WEBRTC=ON -DBUILD_JUPYTER_EXTENSION=ON -DBUILD_EXAMPLES=OFF ..
make -j$(nproc)
```

### Error message

```shell
[ 29%] Linking CXX executable ../../../bin/ShaderLinker
/users/wctaylor/miniconda3/envs/test/bin/ld: CMakeFiles/ShaderEncoder.dir/__/__/__/cmake/ShaderEncoder.cpp.o: in function `MakeString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xae): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xec): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x136): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x14e): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x18d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x270): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x280): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2bf): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3a2): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3d1): undefined reference to `std::__throw_length_error(char const*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3de): undefined reference to `std::__throw_length_error(char const*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text._Z10MakeStringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3fc): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: CMakeFiles/ShaderEncoder.dir/__/__/__/cmake/ShaderEncoder.cpp.o: in function `main':
ShaderEncoder.cpp:(.text.main+0xb4): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x1a0): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x222): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x291): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x2e5): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x3ea): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x48f): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x4e7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x5d3): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x5ea): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x634): undefined reference to `std::__throw_logic_error(char const*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x650): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x6d3): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x6ee): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: ShaderEncoder.cpp:(.text.main+0x709): undefined reference to `operator delete(void*)'
/users/wctaylor/miniconda3/envs/test/bin/ld: CMakeFiles/ShaderEncoder.dir/__/__/__/cmake/ShaderEncoder.cpp.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/ShaderEncoder] Error 1
make[2]: *** [cpp/open3d/visualization/CMakeFiles/ShaderEncoder.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

### Open3D, Python and System information

```markdown
- Operating system: Red Hat Enterprise Linux 7.7
- Python version: Python 3.10.0
- Open3D version: Open3D 0.15.2+dcf94bd2
- System architecture: x86
- Is this a remote workstation?: yes
- How did you install Open3D?: build from source
- Compiler version (if built from source): Clang 12.0.1
```

### Additional information

I understand that RHEL is not officially supported, but any help would be appreciated.

**Comment by ssheorey** [comment] 2023-01-29 19:33
Hi @wctaylor RHEL 7 / CentOS 7 is not supported since it is too old and some of Open3D dependencies do not support the environment. 

@purplebutterfly79 for RHEL 8 / CentOS 8, happy to accept PRs. I believe it just needs minor updates to cmake to find libc++, etc. - the RHEL locations / package names are different.

An easier option on RHEL 8 is to use the precompiled binary packages.

Duplicate of: #4570
Please continue the discussion there.

**Closed by ssheorey** 2023-01-29 19:33 UTC
Labels: build/install issue
