### ISSUE TITLE
Support reading PCD files with intensities

### ISSUE THREAD

**Issue by PingHGao** [isl-org/Open3D#3341] opened 2021-04-27 07:44 UTC
I have a pcd file with below format:
```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z _ intensity _
SIZE 4 4 4 1 4 1
TYPE F F F U F U
COUNT 1 1 1 4 1 12
WIDTH 41175
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 41175
DATA binary
.........binary data...........
```
When I use `pcd = o3d.io.read_point_cloud(pcdfile)` to read this file. I only get XYZ data. Although the number of points is right. I wonder whether Open3D decode the binary data correctly or not.

**Comment by PingHGao** [comment] 2021-05-05 05:25
> Intensities are not supported by the legacy point cloud API. Only 3-channel RGB values. These are supported by the new tensor based API (`open3d.t.*`). Currently you should be able to read XYZI format data from XYZI files with the new API. Support for other formats (e.g. PCD) is in progress.

I found the xyz data read by Open3D is right. However it was somehow weird. I am curious why Open3D can decode the binary data correctly.

**Comment by ssheorey** [comment] 2021-05-13 20:47
Can you clarify this?

> I found the xyz data read by Open3D is right. However it was somehow weird.

The best way for us to help you is if you can provide a small  data file and Open3D code with incorrect behavior.

**Comment by PingHGao** [comment] 2021-05-15 01:36
> Can you clarify this?
> 
> > I found the xyz data read by Open3D is right. However it was somehow weird.
> 
> The best way for us to help you is if you can provide a small data file and Open3D code with incorrect behavior.

As we can see the binary data is in the following formate:
```
FIELDS x y z _ intensity _
SIZE 4 4 4 1 4 1
TYPE F F F U F U
```
However the Open3D only get the xyz data. So I an curious why the Open3d can read the right xyz data from that binary data.

**Comment by hahakid** [comment] 2021-06-17 12:46
@ssheorey it seems that the ReadPointCloudFromXYZI only support by C++, and has no implement on python?

**Comment by meng-zha** [comment] 2021-06-20 13:57
I met the same issue. Is there some new features about reading XYZI on python api? @ssheorey

**Comment by ssheorey** [comment] 2022-01-31 19:38
Hi @hahakid @meng-zha you can read `xyzi` data from a file in Python with `open3d.t.io.read_point_cloud`. Note that the format is a simple text file with no headers.

```bash
$ cat simple.xyzi
0.0000000000 0.0000000000 0.0000000000  0.00
1.0000000000 0.0000000000 0.0000000000  0.25
0.0000000000 1.0000000000 0.0000000000  0.75
0.0000000000 0.0000000000 1.0000000000  1.00
```
```python
>>> import open3d as o3d
>>> xyzi = o3d.t.io.read_point_cloud("simple.xyzi")
>>> xyzi
PointCloud on CPU:0 [4 points (Float64)] Attributes: intensities (dtype = Float64, shape = {4, 1}).
>>> xyzi.point['intensities']
[[0.0],
 [0.25],
 [0.75],
 [1.0]]
Tensor[shape={4, 1}, stride={1, 1}, Float64, CPU:0, 0x5566265aeec0]
```

**Comment by ssheorey** [comment] 2022-01-31 19:41
Closing as duplicate of #3305.

**Closed by ssheorey** 2022-01-31 19:41 UTC
Labels: feature request, io

**Comment by themightyoarfish** [comment] 2023-04-08 16:03
Has there been any progress on custom pcd channels in the last year?
