### ISSUE TITLE
Missing Point Light Shadows

### ISSUE THREAD

**Issue by wpalfi** [isl-org/Open3D#3970] opened 2021-08-23 14:09 UTC
**Describe the bug**
I dont see any shadows when using point lights.

**To Reproduce**
```python
import open3d.visualization.gui as gui
import open3d.visualization.rendering as rendering
import open3d as o3d
import numpy as np

use_point_light = True

gui.Application.instance.initialize()
window = gui.Application.instance.create_window(f"{use_point_light=}", 500, 500)
scene_widget = gui.SceneWidget()
scene_widget.scene = rendering.Open3DScene(window.renderer)
window.add_child(scene_widget)
bbox = o3d.geometry.AxisAlignedBoundingBox([-2, -2, -2], [2, 2, 2])
scene_widget.setup_camera(60, bbox, [0, 0, 0])

material = rendering.Material()
material.base_color = [.5,1,.5,1]
material.shader = "defaultLit"

box1 = o3d.geometry.TriangleMesh.create_box(width=1,height=1,depth=.1).subdivide_midpoint(3)
box1.compute_vertex_normals()
box1.paint_uniform_color([0.1, 0.1, 0.7])
scene_widget.scene.add_geometry("box1", box1, material)

box2 = o3d.geometry.TriangleMesh.create_box(width=.1,height=.1,depth=.3).translate([0,0,.1]).subdivide_midpoint(3)
box2.compute_vertex_normals()
box2.paint_uniform_color([0.1, 0.1, 0.7])
scene_widget.scene.add_geometry("box2", box2, material)

scene_widget.scene.scene.enable_sun_light(False)

def set_light_dir(light_dir):
    scene_widget.scene.scene.remove_light('light')
    if use_point_light:
        scene_widget.scene.scene.add_point_light('light',[1,1,1],-3*light_dir,1e8,1e2,True)
    else:
        scene_widget.scene.scene.add_directional_light('light',[1,1,1],light_dir,1e6,True)

scene_widget.set_on_sun_direction_changed(set_light_dir)
set_light_dir(np.array([-1,-1,0]))
gui.Application.instance.run()
```

**Expected behavior**
I would expect to see shadows with both directional and point lights.

**Screenshots**
With directional light:
![image](https://user-images.githubusercontent.com/18048248/130460991-d2cb6da7-f7eb-4716-a686-ab412e96142b.png)

With point light:
![image](https://user-images.githubusercontent.com/18048248/130461031-f5a6905e-47d5-4af7-9cf2-a0eae1001703.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: 0.13.0+a99c250
- Is this remote workstation?: no
- How did you install Open3D?: pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.13.0+a99c250-cp38-cp38-win_amd64.whl

**Comment by errissa** [comment] 2021-12-08 03:37
I was not able to reproduce the reported crash on any platform with the 0.14.1 release. Please try 0.14.1. I'm closing the issue but if you continue to experience the issue feel free to reopen.

**Closed** 2021-12-08 03:39 UTC
Labels: visualization, rendering
