### ISSUE TITLE
WebRTC rotate, zoom, translate all too slow 

### ISSUE THREAD

**Issue by cjl22ljc** [isl-org/Open3D#5942] opened 2023-02-22 05:29 UTC
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Are the object transformations like rotation supposed to be slow?

**Comment by ssheorey** [comment] 2023-02-24 17:08
Duplicate of #5908 
Please follow up there.

**Closed by ssheorey** 2023-02-24 17:08 UTC
Labels: question
