### ISSUE TITLE
Silent Failure when assigning color to point cloud points, and/or creating coordinate frame triangle mesh.

### ISSUE THREAD

**Issue by zane-morris** [isl-org/Open3D#6878] opened 2024-07-17 18:40 UTC
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

My goal is to generate two triangle mesh objects, and overlay them with the point cloud data that created them. I additionally want each point cloud to have a unique color for its data points, and I want to include a coordinate frame in the visualization window to give a sense of orientation.

I have been able to successfully generate and visualize the mesh, as well as each point cloud, without attempting to add the coordinate frame or adjust the point cloud's color.

If I attempt to add color to the point cloud using ```pc_l.colors = o3d.utility.Vector3dVector(array(len(data_l)*[[1, 0, 0]]))``` (as shown in the "bug reproduction" section below) or attempt to add a coordinate system using 
```cf = o3d.geometry.TriangleMesh.create_coordinate_frame()```, the debug console returns the following error message *[WinError 10054] An existing connection was forcibly closed by the remote host*. When running the code outside the debugger, I get no error message, the program just fails without generating the visualization window.

A nuance to this issue is that when I run the two commands
`pc_l.colors = o3d.utility.Vector3dVector(array(len(data_l)*[[1, 0, 0]]))`
`o3d.visualization.draw_geometries([pc_l,mesh_l])` 
together in the debug console (only hit enter once), the color of the point cloud data is correctly updated and shown on the subsequently opened visualization window. I don't understand why this command would work in this one context, and not in any other. 

### Steps to reproduce the bug

```python
# Imports
from numpy import array, loadtxt
import open3d as o3d

# Read file and create point cloud
data_l, data_r = loadtxt(fname_l), loadtxt(fname_r)
pc_l, pc_r = o3d.geometry.PointCloud(), o3d.geometry.PointCloud()
pc_l.points, pc_r.points = o3d.utility.Vector3dVector(data_l), o3d.utility.Vector3dVector(data_r)

# Assigning Color to PCs
pc_l.colors = o3d.utility.Vector3dVector(array(len(data_l)*[[1, 0, 0]]))

# Adding Coordinate Frame
cf = o3d.geometry.TriangleMesh.create_coordinate_frame()
```

### Error message

From Debug console: [WinError 10054] An existing connection was forcibly closed by the remote host

No error message from terminal when not running in debug mode.

### Expected behavior

The expected behavior is simple. 
1) Have the code either a) provide a more detailed error message if one should exist, or b) consistently have the color of the point clouds be updated and represented accordingly in the visualization window when executing 

```pc_l.colors = o3d.utility.Vector3dVector(array(len(data_l)*[[1, 0, 0]]))```
```o3d.visualization.draw_geometries([pc_l, pc_r,mesh_r,mesh_l])```

2) Have the code either a) provide a more detailed error message if one should exist, or b) have the coordinate frame appear in the visualization window when executing

```cf = o3d.geometry.TriangleMesh.create_coordinate_frame()```
```o3d.visualization.draw_geometries([cf,pc_l, pc_r,mesh_r,mesh_l])```

### Open3D, Python and System information

```markdown
- Operating system: Windows 11 64-bit
- Python version: Python 3.11.7
- Open3D version: 0.18.0
- System architecture: x86
- Is this a remote workstation?: No
- How did you install Open3D?: pip
```

**Comment by rxba** [comment] 2024-07-17 21:37
Hey @zane-morris , I was able to reproduce this issue. Both `create_coordinate_frame()` and assigning to `.colors` caused a segmentation fault.
This issue, like many other current issues like it, seems to be related to version `2.0.0` of `numpy`.

You can fix this by downgrading numpy, e.g. with `pip install numpy==1.26.4`.

**Comment by zane-morris** [comment] 2024-07-18 16:49
Thank you @rxba ! Can confirm that this solved the issue.

**Closed** 2024-07-18 16:49 UTC
Labels: bug

**Comment by chenin-wang** [comment] 2024-08-16 06:49
> Hey @zane-morris , I was able to reproduce this issue. Both `create_coordinate_frame()` and assigning to `.colors` caused a segmentation fault. This issue, like many other current issues like it, seems to be related to version `2.0.0` of `numpy`.
> 
> You can fix this by downgrading numpy, e.g. with `pip install numpy==1.26.4`. Also see #6874 .

it works for me
