### ISSUE TITLE
dense_slam.py Unimplemented device Error

### ISSUE THREAD

**Issue by yhk1515** [isl-org/Open3D#4203] opened 2021-10-27 03:28 UTC
I executed the code as follows.
python dense_slam.py --config default_config.yml
------------------------------------------------------------------------------------------------------------------------------------------
ERROR
![image](https://user-images.githubusercontent.com/50613801/138994988-ba55dd17-6196-448c-88f6-e4bf4c560d21.png)
-------------------------------------------------------------------------------------------------------------------------------------------
What kind of problem is there? Please help me.

**Comment by ozgucbertug** [comment] 2021-11-01 16:05
@yxlao @theNded  - thank you both for being incredibly responsive.

I just had the chance to test the changes both on Windows and Ubuntu. I still receive the `module 'open3d.visualization.rendering' has no attribute 'Material'` error on both when trying to run `dense_slam_gui.py` from the examples. For windows `No module named 'open3d.cpu'` issue also remains. I'm not sure how helpful this would be, but I'm also sharing the system information below:

Windows:

- Operating system: Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: open3d-0.13.0+4dd197ce2
- How did you install Open3D?: build from source

```
cmake -G "Visual Studio 16 2019" -A x64 -DBUILD_CUDA_MODULE=ON -DCMAKE_INSTALL_PREFIX="<open3d_install_directory>" ..

cmake --build . --config Release --target install-pip-package
```

Ubuntu:

-Operating system: Ubuntu 18.04
- Python version: Python 3.8
- Open3D version: open3d-0.13.0+4dd197ce2
- How did you install Open3D?: pip
```
pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.13.0+4dd197c-cp38-cp38-manylinux_2_27_x86_64.whl
```

**Comment by theNded** [comment] 2021-11-01 16:09
The `Material` issue should have been fixed in the [latest example](https://github.com/isl-org/Open3D/blob/master/examples/python/t_reconstruction_system/dense_slam_gui.py#L252). The reason was not the Filament compilation, but a change of API (`Material` -> `MaterialRecord`). Could you please pull the latest changes of the repo and see how it works?
For windows @yxlao could you please confirm the behaviour of CUDA configuration?

**Comment by ozgucbertug** [comment] 2021-11-01 16:13
I can confirm that the latest example is working with the change from `rendering.Material` to `rendering.MaterialRecord`

**Closed** 2021-11-12 14:52 UTC
