### ISSUE TITLE
Visualization blur when utilizing SceneWidget as opposed to Visualizer

### ISSUE THREAD

**Issue by lozino** [isl-org/Open3D#2946] opened 2021-01-26 13:40 UTC
Hi all,

I have recently started toying around with the new GUI, and I am noticing considerable differences between how the geometries are visualized inside a SceneWidget as opposed to inside a Visualizer.

Here is an example:

SceneWidget (using default material with unlitLine shader, boxes are drawn using LineSets)
![SceneWidget](https://user-images.githubusercontent.com/35559435/105851185-01f54c00-5fe3-11eb-9933-e4b55746ceb0.png)

Visualizer (in particular, I am using a VisualizerWithKeyCallback. Again, boxes drawn using the same LineSets as above)
![VisualizerWithKeyCallback](https://user-images.githubusercontent.com/35559435/105851167-fc980180-5fe2-11eb-910e-bdf7e15314c6.png)

More specifically, I am noticing that the boxes look very blurry in the SceneWidget (also, the background color seems to differ, despite it being set to the same value in both cases). Is there a way to make the visualization sharper / more similar to that of Visualizer inside a SceneWidget? Am I doing something wrong? If not, is there a way to integrate the new GUI elements directly inside a Visualizer?

Thank you.

Environment:

Operating system:Ubuntu 20.04
Python version: python 3.8.0
Open3D version: 0.12
Is this remote workstation?: yes (although I tested it on a local machine and the result appears to be the same)
How did you install Open3D?: pip

**Comment by prewettg** [comment] 2021-01-26 22:44
No, you're not doing anything wrong, it's just that there are differences. The old visualizer ("Visualizer") renders using raw OpenGL, whereas the new visualizer uses Filament to render. There are many differences between how Filament and raw OpenGL render, and you've hit two of the major ones:
1) colors: RGB values by themselves do not specify a reproducible color. Filament uses a post-processing tone mapping step to map raw RGB values in the GL buffers to the colormap requested (I think we use sRGB), which ensures that the colors resulting from PBR materials end up within [0, 1]. You can specify a material with `material.sRGB_color = false` and that will sometimes work, however, you should not use this with any of the shaders that have "lit" in their name. Since the background is create behind-the-scenes this option isn't available, although it is something I plan on experimenting with, when time becomes available.
2) Filament does not support arbitrary-width lines, because some of its platforms do not support it (namely, EGL). As a result, we draw lines using triangles, instead of using OpenGL line primitives, which naturally renders differently. You cannot get the exactly the same rendering as the old visualizer (although you *can* render things with physically-based materials with nice shadows, which is impossible with the old visualizer). However, in the case of lines, if you specify a larger value for line_width you will probably get lines which appear both sharper and less pixelated.

It is not possible to use the GUI elements with the old visualizer.

**Comment by lozino** [comment] 2021-02-02 15:50
Hi prewettg,

Thank you for your answer. I had already tried increasing the line width, but the boxes still look heavily blurred, especially when zooming out.

The situation is no different when visualizing point clouds. Here is an example:

Visualizer

![oldviz](https://user-images.githubusercontent.com/35559435/106624384-e3103000-6575-11eb-937d-f42f54615bf7.png)

SceneWidget (I am aware that a compression is performed during GUI interaction to improve performance, this screenshot is taken when the higher quality rendering is generated)

![newviz](https://user-images.githubusercontent.com/35559435/106624411-ea373e00-6575-11eb-8456-bf0595cb1963.png)

I understand the point of OpenGL vs Filament. I guess at this point I am just wondering whether there is something I can do to obtain better quality renderings at the cost of worse performance (looking at what I get, it is almost as if what I obtain is quite heavily compressed). 
If you have some pointers, perhaps something I am missing from the docs, they would be greatly appreciated.

Thank you.

**Comment by errissa** [comment] 2021-02-02 16:08
@lozino Can you share that scene or script that created it?

**Comment by Leerw** [comment] 2021-07-21 10:00
> @lozino Can you share that scene or script that created it?

I have the same issue, SceneWidget rendering result is blury. The rendering quality is not good enough. You can load a common mesh and use SceneWidget to render.

**Comment by stanlewry** [comment] 2021-08-04 14:02
Is there any possible work around for this? It renders the GUI basically unusable

**Comment by errissa** [comment] 2021-12-16 18:56
Once #4441 is merged you will be able to disable the post processing effects that cause the blurring. This was already possible with C++ API but is now also possible in Python.
```
import open3d as o3d
import numpy as np

# Create three random point clouds
rng = np.random.default_rng()
pts1 = rng.random((10000, 3), dtype=np.float32)
t1 = o3d.core.Tensor(pts1)
pcd1 = o3d.t.geometry.PointCloud(t1)
pcd1.point['colors'] = t1
mat = o3d.visualization.rendering.MaterialRecord()
mat.shader = "defaultUnlit"
mat.point_size = 5

render = o3d.visualization.rendering.OffscreenRenderer(800,600)
render.scene.add_geometry("pcd", pcd1, mat)
render.setup_camera(45.0, [0.5, 0.5, 0.5], [0.5, 2, 0.5], [0, 0, 1])

img = render.render_to_image()
o3d.io.write_image("/tmp/default_render.png", img)

# Disable post processing
render.scene.view.set_post_processing(False)
img = render.render_to_image()
o3d.io.write_image("/tmp/no_post_processing.png", img)
```

**Closed** 2021-12-22 13:55 UTC
Labels: visualization, ui
