### ISSUE TITLE
Segmentation fault error when Open3D is built as a shared library

### ISSUE THREAD

**Issue by iretiayo** [isl-org/Open3D#3701] opened 2021-07-07 04:27 UTC
In trying to use Open3D as a shared library, I get a Segmentation fault error which I traced back to [here](https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/visualization/visualizer/Visualizer.cpp#L200) and ultimately crashes at this [line](https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/visualization/visualizer/VisualizerRender.cpp#L70).
The Segfault crash happens when trying to use the visualization component.

The issue can be reproduced when running one of the Open3D examples that uses visualization such as the PointCloud [example](https://github.com/intel-isl/Open3D/blob/master/examples/cpp/PointCloud.cpp).

Steps to reproduce the error:

1. Compile Open3D

```
git clone --recursive https://github.com/intel-isl/Open3D
util/install_deps_ubuntu.sh
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON ..
make
```

2. Test visualization example using any input pointcloud will result in SegFault
```
./bin/examples/PointCloud ../examples/test_data/fragment.pcd
```

Note the `-DBUILD_SHARED_LIBS=ON` flag in step 1 that is used to compile Open3D as shared library. If I take out the flag, the example runs fine.

**Environment details:**
- Operating system: Ubuntu 18.04
- Python version: Python 3.6
- Open3D version: latest commit
- Is this remote workstation?: no
- How did you install Open3D?: built from source ([62390a0](https://github.com/intel-isl/Open3D/commit/62390a04b2b149a82b262f5b004bd19e6ca06d7e))
- Compiler version (if built from source): gcc 7.5.0

**Is there a way to compile Open3D as a shared library?**

**Comment by ssheorey** [comment] 2021-07-07 20:17
Hi @iretiayo thanks for reporting this!

I was not able to reproduce this on Ubuntu 20.04 with the latest master 3ec7a1919. The example worked correctly for me.

Please fill out the bug reporting template (especially all system and environment information) to enable others to reproduce the issue.

**Comment by iretiayo** [comment] 2021-07-08 05:02
@ssheorey Thanks for your prompt reply. I updated the post above with the system details that should reproduce the error. I tried it on two different Ubuntu 18.04 and got the same issue.

**Comment by iretiayo** [comment] 2021-07-09 09:03
Using the same commit ([3ec7a19](https://github.com/intel-isl/Open3D/commit/3ec7a1919e1e27ca4c3ed14db41f4c96cbdfb316)) as @ssheorey on the Ubuntu 18.04 machine, I get the following error when I build with the flag ` -DBUILD_SHARED_LIBS=ON`:

```
./bin/examples/PointCloud: symbol lookup error: ./bin/examples/PointCloud: undefined symbol: _ZN6open3d2io14ReadPointCloudERKSsRNS_8geometry10PointCloudERKNS0_20ReadPointCloudOptionE
```

I do not get any error without the flag.

**Comment by reyanshsolis** [comment] 2021-11-29 13:24
I was not able to reproduce the issue. May you share more information about your system?

**Comment by ssheorey** [comment] 2021-12-13 23:44
Hi @iretiayo I was not able to reproduce on a different Ubuntu 18.04 machine either. Closing this issue. Please re-open if you can reproduce on a clean Ubuntu 18.04 install.

**Closed by ssheorey** 2021-12-13 23:44 UTC
Labels: build/install issue
