### ISSUE TITLE
online-processing.py not working with Cuda

### ISSUE THREAD

**Issue by maohong30** [isl-org/Open3D#3757] opened 2021-07-18 05:23 UTC
Is this problem solved yet? I have the same problem. I installed Open3d from source with DBUILD_WITH_CUDA_MODULE=ON

However, when I tried running 
> online-processing.py --device cuda:0 

the GUI pop up less than 1 sec, it is closed automatically and kernel restarted without error message. 

It is working fine with cpu:0 where I can see the point cloud but it is easily crashed unexpectedly.

I have already reinstalled Open3d many times and also double checked with Cmake to make sure the DBUILD_WITH_CUDA_MODULE is turned on.

I'm running out of idea, please help. Thank you.

Environment:
Open3d: V0.13
Operating system: Windows 10 64-bit
Python version: Python 3.8
Cuda: 10.1
GPU : Nvidia RTX 2070
Camera: Realsense D415
Visual studio 2019
Spyder

_Originally posted by @maohong30 in https://github.com/intel-isl/Open3D/issues/3452#issuecomment-881928997_

**Comment by ssheorey** [comment] 2021-07-20 01:39
Duplicate of #3452

**Closed** 2021-08-07 20:44 UTC
