### ISSUE TITLE
Enable CUDA and ML Ops on Windows

### ISSUE THREAD

**Issue by bakhtiyar-k** [isl-org/Open3D#4644] opened 2022-01-22 13:02 UTC
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hello. I am trying to build Open3D with ML module from source as shown in https://github.com/isl-org/DeepLagrangianFluids. I have CUDA version 10.2, CUDNN 8.3.1, PyTorch 1.8.2, Visual Studio 16 2019 installed. I set `-DBUILD_TENSORFLOW_OPS=OFF` since it is not supported on Windows 10. When I run `cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TENSORFLOW_OPS=OFF -DBUILD_PYTORCH_OPS=ON -DBUILD_CUDA_MODULE=ON` I end up getting the following error:

![изображение](https://user-images.githubusercontent.com/81955278/150638847-69b94081-cd20-49d0-8fe7-4cba42fccd76.png)

The documentation says ABI is set to OFF to ensure compatibility with PyTorch and TensorFlow Python releases
![изображение](https://user-images.githubusercontent.com/81955278/150639477-f928f6b7-0799-4983-98e1-fcec0a0c84a7.png)

How to solve this?

**Comment by benjaminum** [comment] 2022-01-23 14:48
Hi @bakhtiyar-k , you need to add `-DGLIBCXX_USE_CXX11_ABI=OFF` to the cmake command.

**Comment by bakhtiyar-k** [comment] 2022-01-23 15:55
Thank you, @benjaminum! The building was completed but I do not understand why it is not built with PyTorch support. I used `python -c "import open3d.ml.torch as ml3d"` to check. 

![изображение](https://user-images.githubusercontent.com/81955278/150686891-56860648-bdf8-4f2f-927b-4e53f796a0b5.png)

**Comment by yxlao** [comment] 2022-01-25 09:40
From the screenshot, the "config" is completed. But it does not show that the "build" is completed. 

Did you run the `cmake --build xxx` command with `install-pip-package`?

**Comment by bakhtiyar-k** [comment] 2022-01-25 11:44
Should I get a message that confirms a successful build? 

I ran `cmake --build . --config Release --target install-pip-package` and still got this

![изображение](https://user-images.githubusercontent.com/81955278/150970583-8a24139a-c17d-41d1-ab5d-5677e86ceda3.png)

**Comment by bakhtiyar-k** [comment] 2022-01-25 11:45
> From the screenshot, the "config" is completed. But it does not show that the "build" is completed.
> 
> Did you run the `cmake --build xxx` command with `install-pip-package`?

**Comment by bakhtiyar-k** [comment] 2022-01-25 11:49
Sorry, I did not mean to close the issue

**Comment by benjaminum** [comment] 2022-01-25 12:22
Can you check the version `print(o3d.__version__)` and the build config `print(o3d._build_config)` to see if they match the version you have built?

**Comment by bakhtiyar-k** [comment] 2022-01-25 12:43
![изображение](https://user-images.githubusercontent.com/81955278/150979113-0babfc4a-85c6-4079-aa56-08d3209b58af.png)

**Comment by benjaminum** [comment] 2022-01-25 12:48
The open3d that is installed is not the version that you build. The version string should look like `0.14.1+commit hash` for you. You can try uninstalling the open3d in your env and then run the install-pip-package target again to narrow down the problem.

**Comment by bakhtiyar-k** [comment] 2022-01-25 14:43
I uninstalled the open3d and ran the install-pip-package target again. I cannot check the build version without the open3d module output says. 

![изображение](https://user-images.githubusercontent.com/81955278/150998063-d16a2c1e-2baf-4520-ad21-f3a7c020b4ce.png)

**Comment by benjaminum** [comment] 2022-01-26 08:25
Building or installing seems to fail. Can you give more information like how long the build takes and the console output?

**Comment by bakhtiyar-k** [comment] 2022-01-26 11:12
Building takes about an hour or slightly more. I ran the install-pip-package target again and it said that there was a syntax error
![изображение](https://user-images.githubusercontent.com/81955278/151152608-e2a92e04-e55b-4bef-953a-2923cef511be.png)

I opened the file and changed `print res` to `print(res)` and reran the install-pip-package target. Now I get `-fwin64` error

![изображение](https://user-images.githubusercontent.com/81955278/151153115-fb3c15dd-8329-43ff-a889-90736609f368.png)

**Comment by benjaminum** [comment] 2022-01-27 10:27
The `print` problem seems to be a confusion with the python version. Can you check that cmake uses the right python environment?

**Comment by bakhtiyar-k** [comment] 2022-01-27 11:46
I don't know how to check but I only have two versions of python on my computer. The first one is 3.9.7 and the second is 3.7.11 which I use for the build in conda virtual environment.

**Comment by benjaminum** [comment] 2022-01-28 11:46
You can check the cmake configuration with the cmake-gui tool. It shows the configurations in a tabular format.

**Comment by bakhtiyar-k** [comment] 2022-01-28 12:36
![изображение](https://user-images.githubusercontent.com/81955278/151544891-d54cb661-5500-4a6d-97fe-3b8602baaa75.png)

**Comment by benjaminum** [comment] 2022-01-28 13:14
Is `venv1` a new environment that you just created for building Open3D?

**Comment by bakhtiyar-k** [comment] 2022-01-28 13:16
Not just now, I've been using it from the beginning. Its python version is 3.7.11

**Comment by benjaminum** [comment] 2022-01-28 15:41
The problem you show is related to the nasm package. In our CI builds for Windows we build without this package.
To further debug this I think it would make sense to create a new environment.

**Comment by bakhtiyar-k** [comment] 2022-01-28 17:15
I remember getting errors with the ASM_NASM compiler and assembler that I resolved by downloading nasm from pip.

**Comment by benjaminum** [comment] 2022-01-29 08:31
It should build turbojpeg even without nasm. Can you try building in a new environment without nasm?

**Comment by bakhtiyar-k** [comment] 2022-01-29 14:49
I created a new environment without nasm. Configuration was successful but the build wasn't. I had many warning messages of different types, for instance: 

![image](https://user-images.githubusercontent.com/81955278/151665319-e984e1b3-ad42-46c2-8e06-4e78ddd7c1f6.png)

![image](https://user-images.githubusercontent.com/81955278/151665328-e3f8e192-45bc-4bde-8c48-355144b8437d.png)

and finally got the message in red:

![image](https://user-images.githubusercontent.com/81955278/151665470-05371aa9-f555-4e15-a23b-ebebfa68fe43.png)

**Comment by bakhtiyar-k** [comment] 2022-01-29 14:58
If I want to switch to Ubuntu, will launching from Virtual Box be sufficient or you will need to have a full distribution installed?

**Comment by benjaminum** [comment] 2022-01-30 12:03
Not sure if there is GPU acceleration with Virtualbox but CPU inference should work

**Comment by bakhtiyar-k** [comment] 2022-01-30 12:13
https://github.com/isl-org/Open3D/issues/4644#issuecomment-1024925508 is this solvable?

**Comment by benjaminum** [comment] 2022-01-31 08:44
It definitely can be solved but it can take some time. CUDA and ML ops is not a configuration that we test with our CI.

**Comment by ssheorey** [comment] 2022-02-16 23:18
Duplicate of #3495

**Comment by ssheorey** [comment] 2023-02-25 00:07
Please follow this in #3495

**Closed by ssheorey** 2023-02-25 00:07 UTC
Labels: build/install issue, windows, ml, cuda
