### ISSUE TITLE
GCC 11 fails on stringop overflow caused by insufficient profileStr allocation

### ISSUE THREAD

**Issue by emillynge** [isl-org/Open3D#4524] opened 2022-01-03 14:47 UTC
When compiling on arch linux using gcc 11 i got this error:
```cpp
In static member function ‘static std::char_traits<char>::char_type* std::char_traits<char>::move(std::char_traits<char>::char_type*, const char_type*, std::size_t)’,
    inlined from ‘static void std::basic_string<_CharT, _Traits, _Alloc>::_M_move(_CharT*, const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/11.1.0/bits/basic_string.h:3459:21,
    inlined from ‘std::basic_string<_CharT, _Traits, _Allocator>& std::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/11.1.0/bits/basic_string.tcc:703:13,
    inlined from ‘std::basic_string<_CharT, _Traits, _Allocator>& std::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/11.1.0/bits/basic_string.tcc:689:5,
    inlined from ‘std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/11.1.0/bits/basic_string.h:4446:21,
    inlined from ‘std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::operator=(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/include/c++/11.1.0/bits/basic_string.h:3769:28,
    inlined from ‘void TryGLVersion(int, int, bool, bool, int)’ at /home/emil/.cache/yay/open3d/src/open3d/cpp/tools/GLInfo.cpp:48:5:
/usr/include/c++/11.1.0/bits/char_traits.h:397:57: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ writing 24 bytes into a region of size 15 overflows the destination [-Werror=stringop-overflow=]
  397 |         return static_cast<char_type*>(__builtin_memmove(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11.1.0/x86_64-pc-linux-gnu/bits/c++allocator.h:33,
                 from /usr/include/c++/11.1.0/bits/allocator.h:46,
                 from /usr/include/c++/11.1.0/string:41,
                 from /usr/include/c++/11.1.0/bits/locale_classes.h:40,
                 from /usr/include/c++/11.1.0/bits/ios_base.h:41,
                 from /usr/include/c++/11.1.0/ios:42,
                 from /usr/include/c++/11.1.0/istream:38,
                 from /usr/include/c++/11.1.0/sstream:38,
                 from /usr/include/c++/11.1.0/complex:45,
                 from /home/emil/.cache/yay/open3d/src/open3d/build/eigen/src/ext_eigen/Eigen/Core:50,
                 from /home/emil/.cache/yay/open3d/src/open3d/cpp/open3d/camera/PinholeCameraIntrinsic.h:29,
                 from /home/emil/.cache/yay/open3d/src/open3d/cpp/open3d/Open3D.h:31,
                 from /home/emil/.cache/yay/open3d/src/open3d/cpp/tools/GLInfo.cpp:27:

```

The issue stems from the following line:
https://github.com/isl-org/Open3D/blob/aebdb9a4396808edece4c24156e0231dc47a5edd/cpp/tools/GLInfo.cpp#L43

This seems to statically allocate a string of 15 bytes, into which longer strings may be written later.

**Example:** changing `"UnknownProfile"` to `"UnknownProfileUnknownProfile"` fixes the error since the allocated string is now longer than the profiles we could write to it.

**Comment by ssheorey** [comment] 2022-01-07 02:51
Hi @emillynge I can't replicate this on Ubuntu 20.04 with `gcc-11`. Does the following code snippet also produce this error for you (with `-Werror`)? It is also assigning a longer C string to a short C++ string. It builds and runs correctly for me (on `godbolt.org` compiler explorer as well).

```c++
#include <string>
#include <iostream>

int main() {
    std::string testStr = "tt";
    std::cout << testStr.size() << std::endl;
    testStr = "qwertyuiopasdfghjklzxcvbnm";
    std::cout << testStr.size() << std::endl;
}
```

**Comment by ssheorey** [comment] 2022-01-31 19:49
Closing since cannot reproduce. Please reopen if there is more information on reproducing the issue. Also, happy to accept PRs that fix this for you.

**Closed by ssheorey** 2022-01-31 19:49 UTC
Labels: build/install issue
