### ISSUE TITLE
 Why would torch.linalg.inv(tensor.cuda()) return identity matrix if we import open3d before torch?

### ISSUE THREAD

**Issue by zjwzcx** [isl-org/Open3D#5921] opened 2023-02-16 06:36 UTC
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### My Question

Hi, thanks for your awesome work!

The title and the following three demos can show my question:

**Demo 1 (Failed)**

```
>>> import open3d    # <- critical modifications
>>> import torch
>>> a = torch.Tensor([[2., 0., 0.], [0., 3., 0.], [0., 0., 4.]]).cuda()
>>> b = torch.linalg.inv(a)
>>> b
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0')
```

**Demo 2 (Successful)**
```
>>> import torch    # <- critical modifications
>>> import open3d
>>> a = torch.Tensor([[2., 0., 0.], [0., 3., 0.], [0., 0., 4.]]).cuda()
>>> b = torch.linalg.inv(a)
>>> b
tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.2500]], device='cuda:0')
```

**Demo 3 (Successful)**
```
>>> import open3d
>>> import torch
>>> a = torch.Tensor([[2., 0., 0.], [0., 3., 0.], [0., 0., 4.]]).cpu()    # <- critical modifications
>>> b = torch.linalg.inv(a)
>>> b
tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.2500]])
```

My versions are as follows: python (3.7.12), torch (1.10.0+cu113), open3d (0.16.0).

Look forward to your reply :)

**Comment by zjwzcx** [comment] 2023-02-16 06:54
Maybe there is importing conflict between open3D and Pytorch. If so, I think it would be better to report a warning when these confusing special cases occur.

**Comment by ssheorey** [comment] 2023-02-28 23:08
Hi @zjwzcx I cannot reproduce this with the latest version of torch (1.13.1+cu117) or your version (1.10.0+cu113) and Open3D **master** (Python 3.8.8):
```sh
$ pip install --trusted-host www.open3d.org -f http://www.open3d.org/docs/latest
/getting_started.html open3d
....
$ pip show open3d
Name: open3d
Version: 0.16.1+ffd08a9
...
$ pip show torch
Name: torch                                                                                                                             
Version: 1.13.1+cu117
...
$ python -c "import open3d; import torch; a = torch.Tensor([[2., 0., 0.], [0., 3., 0.], [0., 0., 4.]]).cuda(); b = torch.linalg.inv(a); print(b);"
tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.2500]], device='cuda:0')

$ pip install torch==1.10.0+cu113 -f https://download.pytorch.org/whl/torch/
...
$ pip show torch
Name: torch
Version: 1.10.0+cu113
...
python -c "import open3d; import torch; a = torch.Tensor([[2., 0., 0.], [0., 3., 0.], [0., 0., 4.]]).cuda(); b = torch.linalg.inv(a); print(b);"
tensor([[0.5000, 0.0000, 0.0000],
        [0.0000, 0.3333, 0.0000],
        [0.0000, 0.0000, 0.2500]], device='cuda:0')
```
Closing this issue. Please reopen if you can reproduce with the latest Open3D.

**Closed by ssheorey** 2023-02-28 23:08 UTC
Labels: question
