### ISSUE TITLE
Visualization Segmentation Fault (macOS M1 - Kitty Terminal)

### ISSUE THREAD

**Issue by BrianPugh** [isl-org/Open3D#5773] opened 2022-12-08 17:59 UTC
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Any open3d visualization call results in a segmentation fault.

### Steps to reproduce the bug

```python
# Basic visualization test from "Getting Started"
python -c "import open3d as o3d; \
           mesh = o3d.geometry.TriangleMesh.create_sphere(); \
           mesh.compute_vertex_normals(); \
           o3d.visualization.draw(mesh, raw_mode=True)"
```

### Error message

zsh: segmentation fault  python -c

### Expected behavior

No segmentation fault

### Open3D, Python and System information

```markdown
- Operating system: macOS 13.1
- Python version: Python 3.9.9
- Open3D version: output from python: 0.16.1
- System architecture: apple-silicon
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

### Additional information

Open3D visualization use to work on my M1 mac, but then one day it didn't (maybe some homebrew package changed?). It doesn't work in any python virtual environments, either. Today in a last ditch effort, I upgraded my OS from 12.X -> 13.1, which didn't help at all.

**Comment by BrianPugh** [comment] 2022-12-08 18:11
Ok I figured it out (naturally after posting for help, but hopefully this helps people)! I tried multiple terminals, here are the results (all running ZSH):

1. Builtin Terminal; works fine after MacOS prompted me to grant keystroke access.
2. iTerm2; works fine
3. Kitty (the terminal I was using in the post); segmentation fault!

Investigating deeper; will probably close this issue soon, but it sounds like this is **probably** not an Open3D issue.

**Comment by errissa** [comment] 2022-12-09 13:36
@BrianPugh Thanks for this issue report. I confirmed that your example works fine on M1 on Terminal and iTerm. It works fine for me under Kitty too. I'm closing this issue for now but if you find that the issue is somehow Open3D related, please feel free to reopen.

**Closed by errissa** 2022-12-09 13:36 UTC
Labels: bug
