### ISSUE TITLE
C++ ViewControl doesn't work 

### ISSUE THREAD

**Issue by kazu0622** [isl-org/Open3D#2874] opened 2021-01-07 10:24 UTC
- Operating system: Windows 10 64-bit
- Open3D version:0.12
- Is this remote workstation?: no
- How did you install Open3D?: build by VS2019
- Compiler version (if built from source): VS2019

I try to design realtime ViewControl App.
I could get 3dview by initial parameter, but failed to change view angle by changing extrinsic params, like Eigen::Matrix4d_u::Identity();

I'd like to have some suggestion to solve this problem.
Of cource, python edition work well.

My code overview is as below:
	vis_cam.CreateVisualizerWindow();
	vis.CreateVisualizerWindow();
	std::shared_ptr<geometry::LineSet> lineset_ptr(
		new geometry::LineSet);
	*lineset_ptr = lineset;
	vis_cam.AddGeometry(lineset_ptr);
	std::shared_ptr<geometry::PointCloud> pointcloud_ptr(new geometry::PointCloud);
	*pointcloud_ptr = pointcloud;
	vis.AddGeometry(pointcloud_ptr);
	camera::PinholeCameraTrajectory camera;
	visualization::ViewControl viewctrl = vis.GetViewControl();
	camera::PinholeCameraParameters camparam;
	viewctrl.ConvertToPinholeCameraParameters(camparam);
	camparam.extrinsic_ = Eigen::Matrix4d_u::Identity();
	viewctrl.ConvertFromPinholeCameraParameters(camparam);
        while(1){
		vis.UpdateGeometry(pointcloud_ptr);
		vis.PollEvents();
		vis.UpdateRender();
        }

Thanks.

**Comment by UEBoy2019** [comment] 2021-01-08 08:13
> * Operating system: Windows 10 64-bit
> * Open3D version:0.12
> * Is this remote workstation?: no
> * How did you install Open3D?: build by VS2019
> * Compiler version (if built from source): VS2019
> 
> I try to design realtime ViewControl App.
> I could get 3dview by initial parameter, but failed to change view angle by changing extrinsic params, like Eigen::Matrix4d_u::Identity();
> 
> I'd like to have some suggestion to solve this problem.
> Of cource, python edition work well.
> 
> My code overview is as below:
> vis_cam.CreateVisualizerWindow();
> vis.CreateVisualizerWindow();
> std::shared_ptrgeometry::LineSet lineset_ptr(
> new geometry::LineSet);
> *lineset_ptr = lineset;
> vis_cam.AddGeometry(lineset_ptr);
> std::shared_ptrgeometry::PointCloud pointcloud_ptr(new geometry::PointCloud);
> *pointcloud_ptr = pointcloud;
> vis.AddGeometry(pointcloud_ptr);
> camera::PinholeCameraTrajectory camera;
> visualization::ViewControl viewctrl = vis.GetViewControl();
> camera::PinholeCameraParameters camparam;
> viewctrl.ConvertToPinholeCameraParameters(camparam);
> camparam.extrinsic_ = Eigen::Matrix4d_u::Identity();
> viewctrl.ConvertFromPinholeCameraParameters(camparam);
> while(1){
> vis.UpdateGeometry(pointcloud_ptr);
> vis.PollEvents();
> vis.UpdateRender();
> }
> 
> Thanks.

build sucessful in VS2019,but i run cpp file,it always download something and had to wait,    last , it will run failed....

**Comment by kazu0622** [comment] 2021-01-10 08:16
Hi sanskar107,
Thank you for your effort.
Are there any potential bugs in C++ View Control?

**Comment by oguzmustafa** [comment] 2021-02-07 19:56
@kazu0622  So how did you run open3d on visual studio?

**Comment by kazu0622** [comment] 2021-02-08 00:12
@oguzmustafa I'd like to know how to avoid this issue. Now I'm just waiting for fixed version.

**Comment by oguzmustafa** [comment] 2021-02-08 08:47
@kazu0622 Have you tried installing eigen with visual studio nuget?

**Comment by kazu0622** [comment] 2021-02-10 00:24
@oguzmustafa I use eigen attached with 3rdparty's folder. I'm interested if NuGet's Eigen could  solve this issue.
Thanks.

**Comment by Constantin771** [comment] 2021-04-12 02:25
@kazu0622 Did you find a solution to the problem?

**Comment by kazu0622** [comment] 2021-04-12 02:42
@Constantin771 I've been just waiting for being released of bug fixed edition. And I haven't tried using NuGet's Eigen yet.

**Comment by prewettg** [comment] 2021-04-12 17:44
@kazu0622 I'm not clear exactly what the problem is, can you describe in more detail what "fails" looks like? I can see three possible problems. First, I don't think that you'll see any visible difference by setting the identity matrix, since that should be the default value. Second, and more importantly, when you assign the result of `vis.GetViewControl()` you are not assigning it to a reference, but to a value. So `viewctrl` is a copy of the contents of the reference that was returned by `GetViewControl()`; consequently when you change `viewctrl` it does not change the copy owned by `vis`. Finally, even if you did modify the reference, `vis` doesn't know that anything has changed, so you'll need to call `UpdateRender()` to redraw.

**Comment by kazu0622** [comment] 2021-04-13 09:01
@prewettg Thank you for your detail comment.
I certainly do UpdateRender() but the view doesn't change from default one.
Here is my code overview as below:
	visualization::ViewControl viewctrl_pcd = vis_pcd.GetViewControl();
	visualization::ViewControl viewctrl_cam = vis_cam.GetViewControl();
	camera::PinholeCameraParameters camparam_pcd, camparam_cam;
	viewctrl_pcd.ConvertToPinholeCameraParameters(camparam_pcd);
	viewctrl_cam.ConvertToPinholeCameraParameters(camparam_cam);
	camparam_pcd.extrinsic_ = init_cam_extrinsic;
	camparam_cam.extrinsic_ = init_cam_extrinsic;
	viewctrl_pcd.ConvertFromPinholeCameraParameters(camparam_pcd, true);
	viewctrl_cam.ConvertFromPinholeCameraParameters(camparam_cam, true);
	while (1) {
		Eigen::Matrix4d_u cam_extrinsic_tmp = Eigen::Matrix4d_u::Identity();
		camparam_pcd.extrinsic_ = cam_extrinsic_tmp;
		camparam_cam.extrinsic_ = cam_extrinsic_tmp;
		viewctrl_cam.ConvertFromPinholeCameraParameters(camparam_cam, true);
		viewctrl_pcd.ConvertFromPinholeCameraParameters(camparam_pcd, true);
		vis_pcd.UpdateGeometry(pointcloud_ptr);
		vis_cam.UpdateGeometry(lineset_ptr);
		vis_pcd.PollEvents();
		vis_cam.PollEvents();
		vis_pcd.UpdateRender();
		vis_cam.UpdateRender();
	}
	I've set the view with no rotation ,no translation(Eigen::Matrix4d_u::Identity()), but it doesn't work.
	
	Thanks.

**Comment by kazu0622** [comment] 2021-06-24 05:55
I updated open3d from 0.12 to 0.13, but it still doesn't work, unfortunately.

**Comment by jpouderoux** [comment] 2022-03-22 23:07
@kazu0622 As @prewettg explained, ```Visualizer::GetViewControl()``` returns a reference on a ```ViewControl``` instance. In your code, you don't get the reference but a copy of it, so everything you do on it is useless.
So just change:
```
visualization::ViewControl viewctrl_pcd = vis_pcd.GetViewControl();
visualization::ViewControl viewctrl_cam = vis_cam.GetViewControl();
```
to 
```
visualization::ViewControl& viewctrl_pcd = vis_pcd.GetViewControl();
visualization::ViewControl& viewctrl_cam = vis_cam.GetViewControl();
```

**Closed** 2023-07-26 04:01 UTC
Labels: bug, visualization, viewcontrol
