### ISSUE TITLE
Segmentation Fault 11 Error when trying to use textures / uv mapping

### ISSUE THREAD

**Issue by MagJ1** [isl-org/Open3D#4563] opened 2022-01-08 18:57 UTC
### Checklist

- [x] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](http://www.open3d.org/docs/release/) and the [latest documentation](http://www.open3d.org/docs/latest/) (for `master` branch).

### Describe the issue

Dear Developer-Team, 

Unfortunately, I run into a problem, when trying to use textures in open3d. It seems as it is quite the same problem, that occurred in version 0.10 discussed in Github issue #2089 .

I try to map a simple picture on a single triangle mesh. The visualizer opens but there is nothing to see. Once I close it, I get the error message "Segmentation fault: 11" and the visualizer crashes. 

I hope it is nothing, that I do wrong. 

I appreciate every help, thank you very much in advance!

### Steps to reproduce the bug

```python
import open3d as o3d
import numpy as np
import copy


w, h = 10, 10
corners = np.array([
    [0, 0, 0],
    [w, 0, 0],
    [w, h, 0],
])

triangles = np.array([[2, 1, 0]])
mesh = o3d.geometry.TriangleMesh(o3d.utility.Vector3dVector(corners),
o3d.utility.Vector3iVector(triangles))

mesh.textures = [o3d.io.read_image("/Users/myName/Desktop/cover21pilots.png")]

uvs = np.array([(1, 1), (1, 0), (0, 0)])
mesh.triangle_uvs = o3d.utility.Vector2dVector(uvs)

mesh.triangle_material_ids = o3d.utility.IntVector(np.array([np.int32(0)]))

mesh.compute_vertex_normals()

o3d.visualization.draw_geometries([mesh])
```

### Error message

Segmentation fault: 11

### Expected behavior

I expected to happen, that I could see a simple triangle mesh as a plane, mapped with my picture on it. 

### Open3D, Python and System information

```markdown
- Operating system: macOS Monterey 12.1
- Python version: Python 3.9.9
- Open3D version: 0.14.1
- System type: Apple M1
- Is this remote workstation?: no
- How did you install Open3D?: pip3
```

**Comment by theNded** [comment] 2022-01-08 20:21
Cannot reproduce on Ubuntu, Windows, or macOS (not M1).
Do any other visualization examples work on your machine?

**Comment by MagJ1** [comment] 2022-01-08 23:46
Yes, other examples do work!

**Comment by theNded** [comment] 2022-01-09 00:59
White is expected because you didn't assign color to the mesh.

Before moving to debugging can you verify that you are actually using 0.14.1 by printing `o3d.__version__` in your script? Since you are using system `pip3` I suspect a virtual environment is not created and versions may mismatch.

**Comment by MagJ1** [comment] 2022-01-09 07:37
But I don't assign color to the cube as well, but it gets printed. I mean, I don't know but that seemed not logic to me. 

I just let it print the version and it is definitely 0.14.1.

Thanks for your help so far!

**Comment by theNded** [comment] 2022-01-09 17:55
Could you please add this line after import: `o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Debug)` and report what you see? 
Also, it will be helpful to identify which exact line causes the segfault. You may print something every line and check where it stops.

**Comment by MagJ1** [comment] 2022-01-09 18:35
To the first question from you, I get the following printed in my terminal and I still just have a total white visualizer unfortunately. Python crashes after closing the visualizer. The GLFW Error seems normal to me, as I get it all the time. Independently, wether I can print something or not. 

```
[Open3D DEBUG] GLFW init.
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display
[Open3D DEBUG] Add geometry and update bounding box to [(0.0000, 0.0000, 0.0000) - (10.0000, 10.0000, 0.0000)]
Segmentation fault: 11
```

The program runs successfully until the second last line. So, just before 
`o3d.visualization.draw_geometries([mesh])` everything is fine.

After that line, I don't get the expected print into my terminal. 

Thank you very much for your time and energy that you spend in solving the problem!

**Comment by theNded** [comment] 2022-01-09 18:58
@MagJ1 could you please change `draw_geometries` to `draw` and see how it works?
@yxlao @errissa do we have any approach to test the visualizer on an M1 machine? This GLFW error looks suspicious, though it might not affect some of the visualization tasks per comment.

**Comment by MagJ1** [comment] 2022-01-09 19:10
Now, I see a red triangle with some background texture, which looks like some kind of world/ universe.  I get the following printed to my terminal: 

```
FEngine (64 bits) created at 0x7fe4b5800000 (threading is enabled)
FEngine resolved backend: OpenGL
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/defaultLit.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/defaultLitTransparency.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/defaultLitSSR.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/defaultUnlit.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/defaultUnlitTransparency.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/depth.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/unlitGradient.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/normals.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/unlitSolidColor.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/unlitBackground.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/infiniteGroundPlane.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/unlitLine.filamat
[Open3D DEBUG] LoadMaterialFromFile(): /usr/local/lib/python3.9/site-packages/open3d//resources/unlitPolygonOffset.filamat
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[error] GLFW error: Cocoa: Failed to find service port for display
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
```

**Comment by theNded** [comment] 2022-01-09 19:20
Is segfault still there drawing the textured mesh?

**Comment by MagJ1** [comment] 2022-01-09 19:22
segfault? I don't know what this is. 

But, I am sorry, I have to be more detailed. I got of course 2 triangles. One from the two line, that I should put before `mesh.textures = ...` and the other one from the end. 

Both is now the draw function. Not draw_geometries anymore.

**Comment by theNded** [comment] 2022-01-09 19:27
Segfault is short for segmentation fault. So may I regard it as problem solved by switching to `draw`?

**Comment by MagJ1** [comment] 2022-01-09 19:30
Ohhh sure :D

I just see the color red. I actually wanted to have a texture upon the mesh. I don't see that yet unfortunately. I am sorry. 

And I am just wondering, why didn't work the function `draw_geometries`?

**Comment by theNded** [comment] 2022-01-09 19:38
OK, then the problem is still not solved.

@errissa @yxlao we have 2 issues:
1. `draw_geometries` does not work on M1 apple, at least for textured mesh;
2. The direct assignment of uv coordinates and textures seems not to work for the `draw` API, also confirmed on my machine (Ubuntu).

**Comment by errissa** [comment] 2022-01-09 23:36
@yxlao I confirmed that @MagJ1's original example works as expected on my (non-M1) Mac so that must be M1 specific. Can you test? My MBP is still several weeks away.

Regarding the use of the new `draw` API... It does not support the `mesh.textures` or `mesh.triangle_material_ids` parameters of `TriangleMesh`. Instead, the preferred way to set the material properties is with `MaterialRecord`. I modified your script to show how it works:
```
import open3d as o3d
import numpy as np
import copy


w, h = 10, 10
corners = np.array([
    [0, 0, 0],
    [w, 0, 0],
    [w, h, 0],
])

triangles = np.array([[2, 1, 0]])
mesh = o3d.geometry.TriangleMesh(o3d.utility.Vector3dVector(corners),
o3d.utility.Vector3iVector(triangles))
vs = np.array([(1, 1), (1, 0), (0, 0)])
mesh.triangle_uvs = o3d.utility.Vector2dVector(uvs)

mesh.compute_vertex_normals()

mat = o3d.visualization.rendering.MaterialRecord()
mat.albedo_img = o3d.io.read_image("examples/test_data/demo_scene_assets/Wood049_Color.jpg")

o3d.visualization.draw({'name': 'test_mesh', 'geometry': mesh, 'material': mat})
```
which produces the following result:
![2022-01-09-183018_1024x768_scrot](https://user-images.githubusercontent.com/3722407/148705757-3aa83adc-28d6-4741-b350-12a00b2c7fab.png)

**Comment by MagJ1** [comment] 2022-01-09 23:45
It works!!! Thank you so much! 

Do you need any other information? Could I have known, that it works that way? Tbh, I am sometimes a little confused by the documentation, as it seems to me, as it provides several ways to get something to work. But I never know which is the write one.

**Comment by errissa** [comment] 2022-01-09 23:56
We are actively working to document the new visualization API (`draw`). Most of the website documentation uses the old visualizer (`draw_geometries`). In the meantime, the examples in `examples/python/gui` are the best, most current source of information.

**Closed** 2022-01-13 18:00 UTC
Labels: geometry, texture
