### ISSUE TITLE
CUDA TSDF

### ISSUE THREAD

**Issue by bumbastic** [isl-org/Open3D#2609] opened 2020-11-12 16:37 UTC
Hi, I now use Open3D with Kinect for Azuer. I use multiple cameras feeding integration volumes simultaneously. Building meshes of objects coming in to camera views.

I have a small issue. Integration is 'slow' and the work is queuing up in this function. I know a lot of work has been done to enable GPU support for the pipeline in the past. 

Will GPU acceleration be available in a near future release?
If i need this too bad within the next 6 month. Should I try to get the unofficial CUDA release working in my ubuntu 18.04 setup?
Or do you recommend something entirely different?

**Comment by theNded** [comment] 2020-11-18 03:01
It will come in the next release, hopefully in December. Please stay tuned!

**Comment by jsaisagar** [comment] 2020-12-02 11:00
Does Open3D 0.11.2 allow TSDF on CUDA?

Thanks,
Sai

**Comment by manhha1402** [comment] 2020-12-17 10:02
Hi @theNded ,
I have tried to run CUDA TSDF in C++. It worked but there is a bug with CUDA. Sometimes, the program gave the error when integrating the first frame :
`[Open3D INFO] Using device: CUDA:0
0
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)`

**Comment by theNded** [comment] 2020-12-17 14:54
> Hi @theNded ,
> I have tried to run CUDA TSDF in C++. It worked but there is a bug with CUDA. Sometimes, the program gave the error when integrating the first frame :
> `[Open3D INFO] Using device: CUDA:0 0 terminate called after throwing an instance of 'thrust::system::system_error' what(): copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered Aborted (core dumped)`

Hi, thanks for the feedback. Are you using the newest master branch merged yesterday? If so, can you please share your system configuration and possibly the data somewhere? Thanks!

**Comment by theNded** [comment] 2020-12-17 15:00
As mentioned, we have merged #2710 that gives initial support of CUDA TSDF integration. Relevant code are in `examples/cpp/TIntegrateRGBD.cpp` and `examples/python/reconstruction_system/tintegrate_scene.py|ipynb`. Please let us know any potential problems so that we can fix them before the release.

**Comment by manhha1402** [comment] 2020-12-17 15:02
Yes. I used the newest master branch. I tried to run the code several times and most of times, the program works and produces the mesh. I tested with the BundleFusion dataset `copyroom`. Here is code:
```
 std::string data_path = "/home/manhha/copyroom/";
  camera::PinholeCameraIntrinsic intrinsic;
  intrinsic.SetIntrinsics(640,480,583,583,320,240);
 std::string device_code = "cuda:0";
  core::Device device(device_code);
  utility::LogInfo("Using device: {}", device.ToString());

  auto focal_length = intrinsic.GetFocalLength();
  auto principal_point = intrinsic.GetPrincipalPoint();
  Tensor intrinsic_t = Tensor(
        std::vector<float>({static_cast<float>(focal_length.first), 0,
                            static_cast<float>(principal_point.first), 0,
                            static_cast<float>(focal_length.second),
                            static_cast<float>(principal_point.second), 0,
                            0, 1}),
  {3, 3}, Dtype::Float32);

  t::geometry::TSDFVoxelGrid voxel_grid({{"tsdf", core::Dtype::Float32},
                                         {"weight", core::Dtype::UInt16},
                                         {"color", core::Dtype::UInt16}},
                                        3.0f / 512.f, 0.04f, 16, 100, device);
  for (int frame_idx = 0; frame_idx < 4478; frame_idx++)
  {
    // cv::Mat ray_cast;
    std::cout << frame_idx << std::endl;
    std::ostringstream curr_frame_prefix;
    curr_frame_prefix << std::setw(6) << std::setfill('0') << frame_idx;
    std::string cam2world_file = data_path + "frame-" + curr_frame_prefix.str() + ".pose.txt";
    std::string depth_im_file = data_path + "frame-" + curr_frame_prefix.str() + ".depth.png";
    std::string rgb_im_file = data_path + "frame-" + curr_frame_prefix.str() + ".color.jpg";
    std::shared_ptr<geometry::Image> depth_legacy = io::CreateImageFromFile(depth_im_file);
    std::shared_ptr<geometry::Image> color_legacy = io::CreateImageFromFile(rgb_im_file);
    t::geometry::Image depth =
        t::geometry::Image::FromLegacyImage(*depth_legacy, device);
    t::geometry::Image color =
        t::geometry::Image::FromLegacyImage(*color_legacy, device);
    std::ifstream readin(cam2world_file, std::ios::in);
    if (readin.fail() || readin.eof())
    {
      std::cout << "ERROR: Can not read pose file " << cam2world_file << std::endl;
      return false;
    }
    Eigen::Matrix4f cam2world;

    for (int r = 0; r < 4; ++r)
      for (int c = 0; c < 4; ++c)
      {
        readin >> cam2world(r, c);
      }


    Eigen::Matrix4f extrinsic = cam2world.inverse();
    Tensor extrinsic_t =
        core::eigen_converter::EigenMatrixToTensor(extrinsic).Copy(
          device);
    utility::Timer timer;
    timer.Start();
    voxel_grid.Integrate(depth, color, intrinsic_t, extrinsic_t);
    timer.Stop();
    utility::LogInfo("{}: Integration takes {}", frame_idx, timer.GetDuration());
  }
  auto mesh = voxel_grid.ExtractSurfaceMesh();
  auto mesh_legacy = std::make_shared<geometry::TriangleMesh>(
        mesh.ToLegacyTriangleMesh());
  open3d::io::WriteTriangleMesh("mesh_" + device.ToString() + ".ply",
                                *mesh_legacy);
```
The system is running on ubuntu 18.04, cuda 10.2, newest master branch Open3D.

**Comment by theNded** [comment] 2020-12-17 15:56
> Yes. I used the newest master branch. I tried to run the code several times and most of times, the program works and produces the mesh. I tested with the BundleFusion dataset `copyroom`. Here is code:
> 
> ```
>  std::string data_path = "/home/manhha/copyroom/";
>   camera::PinholeCameraIntrinsic intrinsic;
>   intrinsic.SetIntrinsics(640,480,583,583,320,240);
>  std::string device_code = "cuda:0";
>   core::Device device(device_code);
>   utility::LogInfo("Using device: {}", device.ToString());
> 
>   auto focal_length = intrinsic.GetFocalLength();
>   auto principal_point = intrinsic.GetPrincipalPoint();
>   Tensor intrinsic_t = Tensor(
>         std::vector<float>({static_cast<float>(focal_length.first), 0,
>                             static_cast<float>(principal_point.first), 0,
>                             static_cast<float>(focal_length.second),
>                             static_cast<float>(principal_point.second), 0,
>                             0, 1}),
>   {3, 3}, Dtype::Float32);
> 
>   t::geometry::TSDFVoxelGrid voxel_grid({{"tsdf", core::Dtype::Float32},
>                                          {"weight", core::Dtype::UInt16},
>                                          {"color", core::Dtype::UInt16}},
>                                         3.0f / 512.f, 0.04f, 16, 100, device);
>   for (int frame_idx = 0; frame_idx < 4478; frame_idx++)
>   {
>     // cv::Mat ray_cast;
>     std::cout << frame_idx << std::endl;
>     std::ostringstream curr_frame_prefix;
>     curr_frame_prefix << std::setw(6) << std::setfill('0') << frame_idx;
>     std::string cam2world_file = data_path + "frame-" + curr_frame_prefix.str() + ".pose.txt";
>     std::string depth_im_file = data_path + "frame-" + curr_frame_prefix.str() + ".depth.png";
>     std::string rgb_im_file = data_path + "frame-" + curr_frame_prefix.str() + ".color.jpg";
>     std::shared_ptr<geometry::Image> depth_legacy = io::CreateImageFromFile(depth_im_file);
>     std::shared_ptr<geometry::Image> color_legacy = io::CreateImageFromFile(rgb_im_file);
>     t::geometry::Image depth =
>         t::geometry::Image::FromLegacyImage(*depth_legacy, device);
>     t::geometry::Image color =
>         t::geometry::Image::FromLegacyImage(*color_legacy, device);
>     std::ifstream readin(cam2world_file, std::ios::in);
>     if (readin.fail() || readin.eof())
>     {
>       std::cout << "ERROR: Can not read pose file " << cam2world_file << std::endl;
>       return false;
>     }
>     Eigen::Matrix4f cam2world;
> 
>     for (int r = 0; r < 4; ++r)
>       for (int c = 0; c < 4; ++c)
>       {
>         readin >> cam2world(r, c);
>       }
> 
> 
>     Eigen::Matrix4f extrinsic = cam2world.inverse();
>     Tensor extrinsic_t =
>         core::eigen_converter::EigenMatrixToTensor(extrinsic).Copy(
>           device);
>     utility::Timer timer;
>     timer.Start();
>     voxel_grid.Integrate(depth, color, intrinsic_t, extrinsic_t);
>     timer.Stop();
>     utility::LogInfo("{}: Integration takes {}", frame_idx, timer.GetDuration());
>   }
>   auto mesh = voxel_grid.ExtractSurfaceMesh();
>   auto mesh_legacy = std::make_shared<geometry::TriangleMesh>(
>         mesh.ToLegacyTriangleMesh());
>   open3d::io::WriteTriangleMesh("mesh_" + device.ToString() + ".ply",
>                                 *mesh_legacy);
> ```
> 
> The system is running on ubuntu 18.04, cuda 10.2, newest master branch Open3D.

I have run it 20 times, both in Debug and Release mode, and cannot reproduce the problem on my machine. Can you please share more info, including graphics card setup and available gpu memory? In the meantime I will do more tests.

**Comment by manhha1402** [comment] 2020-12-17 16:11
![Screenshot from 2020-12-17 17-07-38](https://user-images.githubusercontent.com/20105284/102512658-91c1e500-408a-11eb-9654-c6c5da71f306.png)
This screenshot I just run. My machine has GPU RTX2070 6GB. The code runs in ROS workspace

**Comment by theNded** [comment] 2020-12-17 17:51
I see, this may have something to do with ROS. Let me check.

**Comment by theNded** [comment] 2020-12-17 23:39
@manhha1402 I have a rough guess. Can you please check these two setups (separately):
1. Change `3.0f / 512.f, 0.04f, 16, 100, device` to `3.0f / 512.f, 0.04f, 16, 27000, device` and see if it still happens in the beginning?
2. Comment out these two lines https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L150 https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L163 and see if it still happens in the beginning (there could be an out-of-memory issue during the process though, which is expected).

**Comment by manhha1402** [comment] 2020-12-18 09:38
> @manhha1402 I have a rough guess. Can you please check these two setups (separately):
> 
>     1. Change `3.0f / 512.f, 0.04f, 16, 100, device` to `3.0f / 512.f, 0.04f, 16, 27000, device` and see if it still happens in the beginning?
> 
>     2. Comment out these two lines https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L150 https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/core/hashmap/CUDA/HashmapCUDA.h#L163 and see if it still happens in the beginning (there could be an out-of-memory issue during the process though, which is expected)?

I tested both two setups separately, the error still happens in both cases (even more) . I will try to test on other machine and without ROS, then let you know.

**Comment by theNded** [comment] 2020-12-19 02:13
Thanks for the update. Can you please try to clone with `--recursive` option and build all the submodules from Open3D? With this, you will only need `-DBUILD_CUDA_MODULE=ON`. I suspect there could be some conflicts/alignment issues with Eigen.

**Comment by manhha1402** [comment] 2020-12-19 15:29
The issue is solved if I run program without ROS and other libraries like OpenCV, PCL. I only keep Open3D and CUDA in CMakeLists.txt file. I still use Open3D with my build flags (use system Eigen). The Eigen version in my machine is 3.3.90. I will do some more test to find out what is problem. I think there could be conflicts with Open3D and ROS.

**Comment by theNded** [comment] 2020-12-19 15:30
Thanks! This is very helpful. I'm not very familiar with ROS but will try to configure and test.

**Comment by theNded** [comment] 2020-12-22 16:30
I have tried to add messages for several issues included in #2805. Once it is merged it may help identify the potential issue.

**Comment by manhha1402** [comment] 2020-12-27 22:41
I have tested the new commit. The CUDA TSDF integration worked fine if I separated it in a standalone ros package. Probably, it conflicts with my code. I will try to fix it. Thank you.

**Comment by manhha1402** [comment] 2020-12-29 19:01
Hi,
I think it would be very helpful if you also add the ray casting to render the surface during the integration.

**Comment by theNded** [comment] 2020-12-29 20:29
> Hi,
> I think it would be very helpful if you also add the ray casting to render the surface during the integration.

Yes, that will be in the next release. I'm planning to make raycasting automatically differentiable when bridged with pytorch.

**Comment by rcffc** [comment] 2021-01-04 16:00
Will the GPU TSDF Integration come to Python anytime soon?

**Comment by theNded** [comment] 2021-01-04 16:13
> Will the GPU TSDF Integration come to Python anytime soon?

https://github.com/intel-isl/Open3D/blob/master/examples/python/reconstruction_system/tintegrate_scene.py

**Comment by jsaisagar** [comment] 2021-01-20 01:19
Hi,

When I am using CUDA TSDF using python, I am getting 0 vertices extracted. While the same dataset, TSDF on CPU is succesfull and am getting nice mesh. I am attaching a sample depth frame for one camera for reference.  May I know what might cause this issue?
Here are the parameters I am using:

voxel_size = 4/1024  
	sdf_trunc = 0.01  
	block_resolution = 16  
	initial_block_count = 800 
	print('here 1')
	volume = o3d.t.geometry.TSDFVoxelGrid(
	{
	    'tsdf': o3d.core.Dtype.Float32,
	    'weight': o3d.core.Dtype.UInt16,
	    'color': o3d.core.Dtype.UInt16
	},
	voxel_size=voxel_size,
	sdf_trunc=sdf_trunc,
![undist_00001](https://user-images.githubusercontent.com/6646353/105113757-921b2900-5aeb-11eb-8835-97e8bdea5fce.png)

	block_resolution=block_resolution,
	block_count=initial_block_count,
	device=device)

Integrate function: 
volume.integrate(
	        depth,color, intrinsic_gpu,
	        extrinsic_alignment_gpu,1000,5.0)

Thanks for any help,
Sai

**Comment by manhha1402** [comment] 2021-02-12 10:08
Hi @theNded ,
After running GPU TSDF, do we have a function to release the GPU memory?
Thank you.

**Comment by theNded** [comment] 2021-11-15 04:08
Now auto CUDA memory management has been implemented, and a [tutorial](http://www.open3d.org/docs/latest/tutorial/t_reconstruction_system/index.html) is available.
Please open new issues wrt the topic.

**Closed by theNded** 2021-11-15 04:08 UTC
Labels: feature request
