### ISSUE TITLE
Segmentation fault (core dumped) caused by `numpy` 2.0.0

### ISSUE THREAD

**Issue by bro-sin** [isl-org/Open3D#6849] opened 2024-07-01 03:52 UTC
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

I follow [General-transformation](https://www.open3d.org/docs/release/tutorial/geometry/transformation.html#General-transformation) and try to run the demo code
```python
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
T = np.eye(4)
T[:3, :3] = mesh.get_rotation_matrix_from_xyz((0, np.pi / 3, np.pi / 2))
T[0, 3] = 1
T[1, 3] = 1.3
print(T)
mesh_t = copy.deepcopy(mesh).transform(T)
o3d.visualization.draw_geometries([mesh, mesh_t])
```
`Segmentation fault (core dumped)` occurred.

For better reproducing this issue, I follow [install-and-run-open3d-apps-in-docker](https://www.open3d.org/docs/release/docker.html#install-and-run-open3d-apps-in-docker) and build a docker image with the following `Dockerfile`:
```Dockerfile
# This could also be another Ubuntu or Debian based distribution
FROM ubuntu:22.04

# Install Open3D system dependencies and pip
RUN apt-get update && apt-get install --no-install-recommends -y \
    libegl1 \
    libgl1 \
    libgomp1 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install Open3D from the PyPI repositories
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir --upgrade open3d

#ADD transformation.py /
RUN echo "\
import open3d as o3d\n\
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()\n\
print(mesh)\n\
"\
    >transformation.py
```
Run this image and run the script with `python3 transformation.py`.  It will cause `Segmentation fault (core dumped)`

I found that this code work if  `numpy<2.0.0`.

Rebuild a docker image with the following `Dockerfile`:
```Dockerfile
# This could also be another Ubuntu or Debian based distribution
FROM ubuntu:22.04

# Install Open3D system dependencies and pip
RUN apt-get update && apt-get install --no-install-recommends -y \
    libegl1 \
    libgl1 \
    libgomp1 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install Open3D from the PyPI repositories
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir --upgrade open3d "numpy<2.0.0"

#ADD transformation.py /
RUN echo "\
import open3d as o3d\n\
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()\n\
print(mesh)\n\
"\
    >transformation.py
```
Run this image and run the script with `python3 transformation.py`. It will get the expected output:
```text
TriangleMesh with 1134 points and 2240 triangles.
```

### Steps to reproduce the bug

```python
import open3d as o3d
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
print(mesh)
```

### Error message

Segmentation fault (core dumped)

### Expected behavior

TriangleMesh with 1134 points and 2240 triangles.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 22.04
- Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
- Open3D version: 0.18.0
- System architecture: x86_64
- Is this a remote workstation?: yes
- How did you install Open3D?: pip
```

**Comment by droghio** [comment] 2024-07-02 02:54
Maybe a duplicate of #6840

**Comment by ssheorey** [comment] 2024-07-13 02:22
Thanks, closing this one in favor of #6840

**Closed by ssheorey** 2024-07-13 02:22 UTC
Labels: bug
