### ISSUE TITLE
Retrieving points using mouse picking

### ISSUE THREAD

**Issue by FarahSaeed** [isl-org/Open3D#4527] opened 2022-01-03 19:18 UTC
Hi

I would like to request a feature to enable user to select and color the regions of point cloud. Since it is currently not available,
I am making a customized application to color parts of point cloud selected by user using polygon selection. I have rendered the point cloud on the screen using opengl. I am trying to map the region (selected on 2d screen) to 3d point cloud. I wanted to know if you can share exact procedure for achieving this and highlight the exact part of code for retrieving the point cloud region segmented using polygon selection and getting the point coordinates using point picking in opengl.

Thank you very much.

**Comment by theNded** [comment] 2022-01-06 04:47
Duplicate of #4326.

**Closed by theNded** 2022-01-06 04:47 UTC
