### ISSUE TITLE
How can i get a 3d visualizer in my own web?

### ISSUE THREAD

**Issue by QiukuZ** [isl-org/Open3D#3882] opened 2021-08-09 07:08 UTC
As 0.13.0's video (https://www.youtube.com/watch?v=pLCVCH7ypI4) show, open3D can add a web server by adding only a line code.And then the video show a demo with web 3D visualizer in a dataset website.
How can I put the 3D visualizer into a personal or project web page?

**Comment by ssheorey** [comment] 2021-08-10 01:42
Duplicate of #3770

**Comment by theNded** [comment] 2021-11-21 01:16
Please refer to possible updates in #3770.

**Closed by theNded** 2021-11-21 01:16 UTC
Labels: feature request
