### ISSUE TITLE
SceneWidget obtains wrong coordinates of point when _on_mouse event

### ISSUE THREAD

**Issue by AkiraGiShinichi** [isl-org/Open3D#4382] opened 2021-12-07 02:37 UTC
**Describe the bug**
Hi!
I try this sample: [mouse-and-point-coord](https://github.com/isl-org/Open3D/blob/master/examples/python/gui/mouse-and-point-coord.py)
It can show the coordinates of point that I click
But It can't be sure that the coordinates are correct. Hence I added the spheres to visualize the clicked points.
It seems that the spheres are displayed at wrong positions, not at where my mouse clicks(I create the spheres at the coordinates that are obtained and displayed)

**To Reproduce**

1. use sample  [mouse-and-point-coord](https://github.com/isl-org/Open3D/blob/master/examples/python/gui/mouse-and-point-coord.py)

2. modify a bit:

```python
import numpy as np
import open3d as o3d
import open3d.visualization.gui as gui
import open3d.visualization.rendering as rendering
import os

SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))

class ExampleApp:

    def __init__(self, cloud):
        # We will create a SceneWidget that fills the entire window, and then
        # a label in the lower left on top of the SceneWidget to display the
        # coordinate.
        app = gui.Application.instance
        self.window = app.create_window("Open3D - GetCoord Example", 1024, 768)
        # Since we want the label on top of the scene, we cannot use a layout,
        # so we need to manually layout the window's children.
        self.window.set_on_layout(self._on_layout)
        self.widget3d = gui.SceneWidget()
        self.window.add_child(self.widget3d)
        self.info = gui.Label("")
        self.info.visible = False
        self.window.add_child(self.info)

        self.widget3d.scene = rendering.Open3DScene(self.window.renderer)

        self.mat = rendering.Material()
        self.mat.shader = "defaultUnlit"
        # Point size is in native pixels, but "pixel" means different things to
        # different platforms (macOS, in particular), so multiply by Window scale
        # factor.
        self.mat.point_size = 3 * self.window.scaling
        self.widget3d.scene.add_geometry("Point Cloud", cloud, self.mat)

        bounds = self.widget3d.scene.bounding_box
        center = bounds.get_center()
        self.widget3d.setup_camera(60, bounds, center)
        self.widget3d.look_at(center, center - [0, 0, 3], [0, -1, 0])

        self.widget3d.set_on_mouse(self._on_mouse_widget3d)

        self.picked_points = []

    def _on_layout(self, layout_context):
        r = self.window.content_rect
        self.widget3d.frame = r
        pref = self.info.calc_preferred_size(layout_context,
                                             gui.Widget.Constraints())
        self.info.frame = gui.Rect(r.x,
                                   r.get_bottom() - pref.height, pref.width,
                                   pref.height)

    def _on_mouse_widget3d(self, event):
        # We could override BUTTON_DOWN without a modifier, but that would
        # interfere with manipulating the scene.
        if event.type == gui.MouseEvent.Type.BUTTON_DOWN and event.is_modifier_down(
                gui.KeyModifier.CTRL):

            def depth_callback(depth_image):
                # Coordinates are expressed in absolute coordinates of the
                # window, but to dereference the image correctly we need them
                # relative to the origin of the widget. Note that even if the
                # scene widget is the only thing in the window, if a menubar
                # exists it also takes up space in the window (except on macOS).
                x = event.x - self.widget3d.frame.x
                y = event.y - self.widget3d.frame.y
                # Note that np.asarray() reverses the axes.
                depth = np.asarray(depth_image)[y, x]

                if depth == 1.0:  # clicked on nothing (i.e. the far plane)
                    text = ""
                else:
                    world = self.widget3d.scene.camera.unproject(
                        event.x, event.y, depth, self.widget3d.frame.width,
                        self.widget3d.frame.height)
                    text = "({:.3f}, {:.3f}, {:.3f})".format(
                        world[0], world[1], world[2])

                self.picked_points.append(world)

                # This is not called on the main thread, so we need to
                # post to the main thread to safely access UI items.
                def update_label():
                    self.info.text = text
                    self.info.visible = (text != "")

                    # We are sizing the info label to be exactly the right size,
                    # so since the text likely changed width, we need to
                    # re-layout to set the new frame.
                    self.window.set_needs_layout()

                    sphere = o3d.geometry.TriangleMesh.create_sphere(radius=0.01)
                    sphere.paint_uniform_color([0.1, 0.1, 0.7])
                    sphere.translate(world)
                    self.widget3d.scene.add_geometry(f"point {len(self.picked_points)}", sphere, self.mat)

                gui.Application.instance.post_to_main_thread(
                    self.window, update_label)

            self.widget3d.scene.scene.render_to_depth_image(depth_callback)
            return gui.Widget.EventCallbackResult.HANDLED
        return gui.Widget.EventCallbackResult.IGNORED


def main():
    app = gui.Application.instance
    app.initialize()

    # This example will also work with a triangle mesh, or any 3D object.
    # If you use a triangle mesh you will probably want to set the material
    # shader to "defaultLit" instead of "defaultUnlit".
    cloud = o3d.io.read_point_cloud(SCRIPT_DIR +
                                    "/../../test_data/ICP/cloud_bin_0.pcd")
    ex = ExampleApp(cloud)

    app.run()


if __name__ == "__main__":
    main()
```

3. See error

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/60541650/144955512-51ab8da4-517a-45c3-9562-013bad46c7b4.png)

**Environment (please complete the following information):**

- Operating system: Windows 10 64-bit
- Python version: Python 3.8
- Open3D version: Open3D 0.13.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

**Comment by errissa** [comment] 2021-12-14 14:16
Duplicate of #4244

**Closed** 2021-12-29 19:44 UTC
Labels: bug
