### ISSUE TITLE
Any plan for mesh parameterization? 

### ISSUE THREAD

**Issue by manhha1402** [isl-org/Open3D#996] opened 2019-05-30 21:22 UTC
Hi,
After reconstructing triangle mesh, I would like to do mesh parameterization, such as Least Squares Conformal Mappings (LSCM). It is useful for mesh processing and texture mapping.
Would you like to add this feature ?
Thanks

**Comment by qianyizh** [comment] 2019-05-31 06:22
We are considering features like this. @griegler @germanros1987 FYI.

**Comment by ipa-mah** [comment] 2019-06-02 19:41
thanks

**Comment by rupeshchandgude** [comment] 2019-09-06 09:09
Is LSCM is available in open3D now?

**Comment by dperyel** [comment] 2022-06-15 19:01
@qianyizh, could you please share in the thread if you decided to add mesh parametrization algorithms or not?
Having LSCM or calculations of harmonic weights would be beneficial features to have.

Even though the issue is closed, the topic is well-indexed in google search results. (-:

**Comment by benjaminum** [comment] 2022-08-09 16:25
We are working on adding UVAtlas in #5376

**Comment by benjaminum** [comment] 2023-01-15 08:25
Closing. uvatlas is now available in `open3d.t.geometry.TriangleMesh.compute_uvatlas()`

**Closed by benjaminum** 2023-01-15 08:25 UTC
Labels: feature request
