### ISSUE TITLE
Python 3.10 wheel

### ISSUE THREAD

**Issue by Drarig29** [isl-org/Open3D#4535] opened 2022-01-04 18:39 UTC
Hi! As suggested [here](https://github.com/isl-org/Open3D/issues/3983#issuecomment-985825097), I'm opening this issue to track the Python 3.10 wheel availability.

References to dependencies progress regarding Python 3.10 support:
- Tensorflow: https://github.com/tensorflow/tensorflow/issues/52324 ([tf2.8-rc0](https://github.com/tensorflow/tensorflow/releases/tag/v2.8.0-rc0) supports Python 3.10 except on Windows)
- Pytorch: https://github.com/pytorch/pytorch/issues/66424

**Comment by friggog** [comment] 2022-04-11 08:19
For those not interested in using the ML side of things (particularly I want to use trimesh's [simplify_quadric_decimation](https://github.com/mikedh/trimesh/blob/30cdb8129fbd1f5c8ed65b3740785c235de8e29f/trimesh/base.py#L2458) which is just a wrapper around Open3D's) is it possible to publish the base module for 3.10 without support for ML, or just without support for torch?

**Comment by johnthagen** [comment] 2022-05-16 20:33
Pytorch 1.11 is released with Python 3.10 support (3.10 wheels): https://pypi.org/project/torch/#files

**Comment by dvicini** [comment] 2022-07-19 16:11
It would be very useful to have Python 3.10 wheels. Any update on this?

**Comment by jackjansen** [comment] 2022-07-30 13:27
Question: the issue is closed from the point of view of the Open3D developers, but not yet from the point of view of the Open3D users (like myself): for us its only closed when a new release is created.

Can I ask that you keep the bug open until that happens?

**Comment by jhultman** [comment] 2022-07-31 19:21
@jackjansen I think the python 3.10 wheels have been added now, at least for development version of open3d. Not sure if there is a stable release yet. You can try:
 
`pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.15.2+21a9779-cp310-cp310-manylinux_2_27_x86_64.whl`

Refer to the table [here](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).

**Comment by jackjansen** [comment] 2022-07-31 19:48
@jhultman thanks for the heads up, and the prereleases are great for developing, but I don't want to base my CI/CD's on them, let alone my distributions.

So only when the Open3D stable release is out I can up my various projects to that release, and therefore to Python 3.10, and then look at what that does for all the other dependencies, on various platforms...

**Comment by ssheorey** [comment] 2022-08-01 12:03
Re-opening issue till Open3D 0.16 is released.

**Comment by johnthagen** [comment] 2022-09-18 12:22
@ssheorey Is there any timeline or roadmap community members can follow to track when 0.16 will be released?

**Comment by chibai** [comment] 2022-10-08 06:48
I need python3.10, too~: )

**Comment by chibai** [comment] 2022-10-09 09:02
> @jackjansen I think the python 3.10 wheels have been added now, at least for development version of open3d. Not sure if there is a stable release yet. E.g. on linux you can try:
> 
> `pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.15.2+21a9779-cp310-cp310-manylinux_2_27_x86_64.whl`
> 
> Refer to the table [here](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).

Is the link broken?? Cause I can not download the file~~

**Comment by chlongv** [comment] 2022-10-10 06:41
> > @jackjansen I think the python 3.10 wheels have been added now, at least for development version of open3d. Not sure if there is a stable release yet. E.g. on linux you can try:
> > `pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.15.2+21a9779-cp310-cp310-manylinux_2_27_x86_64.whl`
> > Refer to the table [here](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
> 
> Is the link broken?? Cause I can not download the file~~

It seems the link's broken indeed. Looking at the CI (https://github.com/isl-org/Open3D/actions/runs/3159931445/jobs/5143774455), this should be the last uploaded python-wheels package (10 days ago): https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.15.2+f17d4d2-cp310-cp310-manylinux_2_27_x86_64.whl

There is probably a data retention script that cleans up older dev builds and there are no more available since the CI hasn't run for 10 days on master.

**Comment by chibai** [comment] 2022-10-10 07:40
> https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.15.2+f17d4d2-cp310-cp310-manylinux_2_27_x86_64.whl

Well, I tried the link~~ It seems the most fresh link is broken, too

**Comment by chibai** [comment] 2022-10-10 07:44
> > > @jackjansen I think the python 3.10 wheels have been added now, at least for development version of open3d. Not sure if there is a stable release yet. E.g. on linux you can try:
> > > `pip install --user --pre https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.15.2+21a9779-cp310-cp310-manylinux_2_27_x86_64.whl`
> > > Refer to the table [here](http://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
> > 
> > 
> > Is the link broken?? Cause I can not download the file~~
> 
> It seems the link's broken indeed. Looking at the CI (https://github.com/isl-org/Open3D/actions/runs/3159931445/jobs/5143774455), this should be the last uploaded python-wheels package (10 days ago): https://storage.googleapis.com/open3d-releases-master/python-wheels/open3d-0.15.2+f17d4d2-cp310-cp310-manylinux_2_27_x86_64.whl
> 
> There is probably a data retention script that cleans up older dev builds and there are no more available since the CI hasn't run for 10 days on master.

Well, it seems the most fresh link is still broken~~

**Comment by johnthagen** [comment] 2022-10-21 23:48
Open3D 0.16.0 has been released with 3.10 wheels: https://pypi.org/project/open3d/0.16.0/

**Comment by itsb** [comment] 2022-10-21 23:53
Missing linux wheels for python 3.8 and 3.9.
https://pypi.org/project/open3d/0.16.0/#files
Is that a compatibility issue or a build system bug?

**Closed** 2022-10-27 15:42 UTC
Labels: feature request, build/install issue
