### ISSUE TITLE
Issue on online-processing.py (update_geometry() + mouse control crash on Windows)

### ISSUE THREAD

**Issue by hwy1992129** [isl-org/Open3D#3452] opened 2021-05-16 22:33 UTC
Hello,
I run online-processing.py. It doesn't work. Probably I made some mistakes in the installation.

**Describe the bug**
The GUI pop-up for less than 1 sec and is closed.
There is no error in the console. As shown below.

```
[Open3D INFO] Capture started with RealSense camera f1120909
[Open3D INFO] Recording [Paused] to bag file 2021-05-16_20-17-04.bag
INFO:root:{
        "color_format" : "RGB8",
        "depth_format" : "Z16",
        "depth_scale" : 3999.999755859375,
        "device_name" : "Intel RealSense L515",
        "fps" : 30.0,
        "height" : 720,
        "intrinsic_matrix" :
        [
                901.40374755859375,
                0.0,
                0.0,
                0.0,
                901.88421630859375,
                0.0,
                643.6456298828125,
                346.04803466796875,
                1.0
        ],
        "serial_number" : "f1120909",
        "stream_length_usec" : 0,
        "width" : 1280
}

FEngine (64 bits) created at 000001F57ACF1050 (threading is enabled)
FEngine resolved backend: OpenGL
```

I add a device argument using cuda:0. It has an error, but GUI is not closed. The console displays the information below. (I just want to check whether it works with cuda:0. cpu:0 is ok, but it doesn't work as mentioned above.)

```
[Open3D INFO] Capture started with RealSense camera f1120909
[Open3D INFO] Recording [Paused] to bag file 2021-05-17_20-46-40.bag
INFO:root:{
        "color_format" : "RGB8",
        "depth_format" : "Z16",
        "depth_scale" : 3999.999755859375,
        "device_name" : "Intel RealSense L515",
        "fps" : 30.0,
        "height" : 720,
        "intrinsic_matrix" :
        [
                901.40374755859375,
                0.0,
                0.0,
                0.0,
                901.88421630859375,
                0.0,
                643.6456298828125,
                346.04803466796875,
                1.0
        ],
        "serial_number" : "f1120909",
        "stream_length_usec" : 0,
        "width" : 1280
}

FEngine (64 bits) created at 000001BAB7578050 (threading is enabled)
FEngine resolved backend: OpenGL
Exception in thread PipelineModel:
Traceback (most recent call last):
  File "C:\Users\hwy19\Miniconda3\envs\dacaa\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\hwy19\Miniconda3\envs\dacaa\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "online-processing.py", line 178, in run
    if self.pcd_frame.is_empty():
AttributeError: 'NoneType' object has no attribute 'is_empty'
```

**To Reproduce**
I don't remember all the details.
I think...
I installed open3D to an existed virtual environment via "pip install open3d".
It seems that the device cannot be detected, because it is L515
According to [#3006 ](https://github.com/intel-isl/Open3D/issues/3006), I uninstalled it and Build from source. I uninstalled my old visual studio and installed visual studio 2019

I followed the documentation, Cloning Open3D. My OS system is Win10, I used cmake GUI to set up the value, Configure and Generate.
I run the all the commands below in my console,
```
cmake --build . --config Release --target ALL_BUILD
cmake --build . --config Release --target INSTALL
cmake --build . --config Release --target install-pip-package
cmake --build . --config Release --target python-package
cmake --build . --config Release --target pip-package
cmake --build . --config Release --target conda-package
```
Finally, I ran ```python -c "import open3d; print(open3d)"```, it works.
I attempted to run online-processing.py.

**Environment (please complete the following information):**
- Operating system: Windows 10 64-bit
- Python version: Python 3.6

**Additional context**
How to uninstall Open3D that is built from source from my virtual environment? It is a big mistake that I installed it in the existed virtual environment. I guess I will create a new virtual environment for Open3D only, but I don't want to delete the virtual environment.....

**Comment by ssheorey** [comment] 2021-05-17 18:48
How did you install Open3D? Please fill out the bug reporting template details (platform, OS, etc.)

**Comment by hwy1992129** [comment] 2021-05-17 19:34
> How did you install Open3D? Please fill out the bug reporting template details (platform, OS, etc.)

I edited the issue...

**Comment by ssheorey** [comment] 2021-05-17 21:36
Thanks @hwy1992129 some suggestions:

- You can use development wheels corresponding to the latest master commit from here:
http://www.open3d.org/docs/latest/getting_started.html#development-version-pip
The Windows wheels are built **without** CUDA, by default.
- For CUDA support, please ensure that you provide `-DBUILD_WITH_CUDA_MODULE=ON` to `cmake` during the config step.
- To uninstall Open3D from the existing venv, `pip uninstall open3d` should work. If it doesn't please let us know what error message you get. If you don't want to install it, you can alternatively add `<Open3D_folder>/build/lib/python_package` to your `PYTHONPATH` and `python -c "import open3d"` should work.

Can you run this test script and provide the output?

    python -m pytest -s test python/test/t/io/test_realsense.py

This script connects to a camera and captures a frame from it.

**Comment by hwy1992129** [comment] 2021-05-18 01:11
@ssheorey I created a new environment and install open3d via wheels.. I install cuda 10.1 today. The result of online-processing.py is the same as before.
In both environments, I can't run 
`python -m pytest -s test python/test/t/io/test_realsense.py`
`No module named pytest`
Is the problem caused by the environment variable?

I have a question. If I install via pip, do I need to build from source....?
Build from source is only for C++, unless I build the python package via cmake and install it?

**Comment by hwy1992129** [comment] 2021-05-18 03:34
@ssheorey Sorry, I don't pytest is a package.
I got the result below.
```
(open3d) E:\xxxxxx\xxxxx\xxxx\open3D\Open3D\python\test\t\io>pytest test_realsense.py
================================================= test session starts =================================================
platform win32 -- Python 3.6.13, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: E:\xxxxxx\xxxxx\xxxx\open3D\Open3D\python
collected 2 items

test_realsense.py sF                                                                                             [100%]

====================================================== FAILURES =======================================================
________________________________________________ test_RealSenseSensor _________________________________________________

    @pytest.mark.skipif(not hasattr(o3d.t.io, 'RealSenseSensor'),
                        reason="Not built with librealsense")
    def test_RealSenseSensor():

        o3d.t.io.RealSenseSensor.list_devices()
        rs_cam = o3d.t.io.RealSenseSensor()
        bag_filename = "test_record.bag"
        try:
            rs_cam.init_sensor(o3d.t.io.RealSenseSensorConfig(), 0, bag_filename)
            rs_cam.start_capture(True)  # true: start recording with capture
            im_rgbd = rs_cam.capture_frame(True,
                                           True)  # wait for frames and align them
            assert im_rgbd.depth.rows == im_rgbd.color.rows
            assert im_rgbd.depth.columns == im_rgbd.color.columns
            rs_cam.stop_capture()
            assert os.path.exists(bag_filename)
>           os.remove(bag_filename)
E           PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'test_record.bag'

test_realsense.py:125: PermissionError
------------------------------------------------ Captured stdout call -------------------------------------------------
[Open3D INFO] [0] Intel RealSense L515: f1120909
[Open3D INFO]   color_format: [RS2_FORMAT_BGR8 | RS2_FORMAT_BGRA8 | RS2_FORMAT_RGB8 | RS2_FORMAT_RGBA8 | RS2_FORMAT_Y16 | RS2_FORMAT_YUYV]
[Open3D INFO]   color_resolution: [1280,720 | 1920,1080 | 960,540]
[Open3D INFO]   color_fps: [15 | 30 | 6 | 60]
[Open3D INFO]   depth_format: [RS2_FORMAT_Z16]
[Open3D INFO]   depth_resolution: [1024,768 | 320,240 | 640,480]
[Open3D INFO]   depth_fps: [30]
[Open3D INFO]   visual_preset: [RS2_L500_VISUAL_PRESET_CUSTOM | RS2_L500_VISUAL_PRESET_DEFAULT | RS2_L500_VISUAL_PRESET_LOW_AMBIENT | RS2_L500_VISUAL_PRESET_MAX_RANGE | RS2_L500_VISUAL_PRESET_NO_AMBIENT | RS2_L500_VISUAL_PRESET_SHORT_RANGE]
[Open3D INFO] Open3D only supports synchronized color and depth capture (color_fps = depth_fps).
[Open3D INFO] Capture started with RealSense camera f1120909
[Open3D INFO] Recording to bag file test_record.bag
[Open3D INFO] Capture stopped.
=============================================== short test summary info ===============================================
FAILED test_realsense.py::test_RealSenseSensor - PermissionError: [WinError 32] The process cannot access the file be...
============================================ 1 failed, 1 skipped in 6.01s =============================================

```

**Comment by hwy1992129** [comment] 2021-05-18 06:32
@ssheorey Does Open3D-ML work in windows? I check DBUILD_PYTORCH_OPS, DBUILD_TENSORFLOW_OPS, DBUNDLE_OPEN3D_ML, and add path to DOPEN3D_ML_ROOT, but I got an error... I find [issues 2507](https://github.com/intel-isl/Open3D/issues/2507). The ML doesn't work in windows?

**Comment by hwy1992129** [comment] 2021-05-18 16:57
@ssheorey I think I used wheel installation before. I got an error now via Build from source like [#3006](https://github.com/intel-isl/Open3D/issues/3006),
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'open3d.cuda.pybind.t.io' has no attribute 'RealSenseSensor'
```
I tried different installations... Build from source, pip install open3d, install via a downloaded wheel... All of them have some issues.....

**Comment by ssheorey** [comment] 2021-05-18 18:03
> I have a question. If I install via pip, do I need to build from source....?
No you don't if you are happy with the built-in features. 

> Build from source is only for C++, unless I build the python package via cmake and install it?
You can build the Python wheel from source as well if you want to customize it.

**Comment by ssheorey** [comment] 2021-05-18 18:19
The test results look good to me. The camera was detected and a frame was captured. There is an updated test in `master` that doesn't try cleaning up the file (which gives this permission error on Windows) and it should also run the first test that was skipped here -- reading from RSbag video file. You can also modify the test to inspect the captured frame if you want to make sure it looks OK.

Let's go with this simple setup:
- Open3D **devel** wheel installed through pip (**not** built from source, no CUDA) in a clean virtual env.
- Can you run `online-processing.py` (from `master`)? If it doesn't work, is there any output or error message?

**Comment by ssheorey** [comment] 2021-05-18 18:28
> @ssheorey Does Open3D-ML work in windows? I check DBUILD_PYTORCH_OPS, DBUILD_TENSORFLOW_OPS, DBUNDLE_OPEN3D_ML, and add path to DOPEN3D_ML_ROOT, but I got an error... I find [issues 2507](https://github.com/intel-isl/Open3D/issues/2507). The ML doesn't work in windows?

3DML in Windows is unsupported. We would welcome user contributions (PRs) in this area.

**Comment by hwy1992129** [comment] 2021-05-18 18:44
@ssheorey I reinstall open3D a few times using different methods. However, I added cuda in build from source.
**Pip install open3D**
It does not support L515. It can't get L515 device.
I gave up this one.

**Build from source**
I use cmake gui and check cuda.
I only Create Python package in build/lib by
```cmake --build . --config Release --target python-package```
 and add it to PYTHONPATH.
"import open3d" is fine. However, it has an error, ```AttributeError: module 'open3d.cpu.pybind.t.io' has no attribute 'realsensesensor'```, when testing ```o3d.t.io.RealSenseSensor()```
Then, I run ```cmake --build . --config Release --target install-pip-package```. The AttributeError is gone.
I run the script twice with/without cuda.
The result of online-processing.py is the same as I asked before, though I checked cuda.


Install open3D from wheel.
I run the script twice with/without cuda.
The result of online-processing.py is the same as I asked before. (There is no cuda in this installation)

**Comment by ssheorey** [comment] 2021-05-28 00:36
Hi @hwy1992129 We've updated the Windows build to ensure error messages are printed out. Please install the latest development wheel, update your Open3D repo and retry the demo (with CPU first). Let us know what error message is shown.
-

**Comment by hwy1992129** [comment] 2021-05-28 04:23
@ssheorey It works with CPU. It is slow and is easy to be closed unexpectedly(crashed?). There is no error shown in the console. The open3D is installed via wheel. I don't know whether it works with CUDA.
```
[Open3D INFO] Capture started with RealSense camera f1120909
[Open3D INFO] Recording [Paused] to bag file 2021-05-28_00-15-07.bag
INFO:root:{
        "color_format" : "RGB8",
        "depth_format" : "Z16",
        "depth_scale" : 3999.999755859375,
        "device_name" : "Intel RealSense L515",
        "fps" : 30.0,
        "height" : 720,
        "intrinsic_matrix" :
        [
                901.40374755859375,
                0.0,
                0.0,
                0.0,
                901.88421630859375,
                0.0,
                643.6456298828125,
                346.04803466796875,
                1.0
        ],
        "serial_number" : "f1120909",
        "stream_length_usec" : 0,
        "width" : 1280
}

FEngine (64 bits) created at 000001CDE67CD050 (threading is enabled)
FEngine resolved backend: OpenGL
```

**Comment by maohong30** [comment] 2021-06-15 14:25
I'm also facing a similar error when running online_processing.py.  What actually causes the error as shown below.  

> AttributeError: 'NoneType' object has no attribute 'is_empty'

**Comment by maohong30** [comment] 2021-07-17 17:11
Is this problem solved yet? I have the same problem. I installed Open3d from source with DBUILD_WITH_CUDA_MODULE=ON

However, when I tried running 
> online-processing.py --device cuda:0 

the GUI pop up less than 1 sec, it is closed automatically and kernel restarted without error message. 

It is working fine with cpu:0 where I can see the point cloud but it is easily crashed unexpectedly.

I have already reinstalled Open3d many times and also double checked with Cmake to make sure the DBUILD_WITH_CUDA_MODULE is turned on.

I'm running out of idea, please help. Thank you.

Environment:
Open3d: V0.13
Operating system: Windows 10 64-bit
Python version: Python 3.8
Cuda: 10.1
Realsense D415
Visual studio 2019
Spyder

**Comment by ssheorey** [comment] 2021-07-20 01:38
Hi @hwy1992129 @maohong30 This is a Windows specific issue and I don't have a Windows machine to reproduce this. It would be great if someone with Windows can help with debugging by following these steps:
- Start with the the official python wheel `pip install open3d`. CUDA is not available.
- Add `o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Debug)` after `import open3d as o3d` to print out the debug logs.
- Add some print statements to figure out the location of the crash and let us know. Paste in the debug logs.
- Once we are able to run the CPU version correctly, we can debug the CUDA version in a similar manner.

**Comment by maohong30** [comment] 2021-07-20 07:25
Hi @ssheorey Thanks for the quick reply. I followed your instructions.

- I reinstalled with  `pip install open3d` which is without CUDA
- Added `o3d.utility.set_verbosity_level(o3d.utility.VerbosityLevel.Debug)` after import `open3d as o3d` to print out the debug logs.

The GUI runs perfectly in the beginning but when I started to zoom in, zoom out and rotating the point cloud, it crashed and kernel was restarted. 

> run online-processing.py --camera-config ../reconstruction_system/config/D415.json --device cpu:0
> [Open3D DEBUG] RS2_FORMAT_ANY -> ANY
> [Open3D DEBUG] RS2_FORMAT_ANY -> ANY
> [Open3D DEBUG] RS2_FORMAT_RGB8 -> RGB8
> [Open3D DEBUG] RS2_FORMAT_Z16 -> Z16
> INFO:root:{
> 	"color_format" : "RGB8",
> 	"depth_format" : "Z16",
> 	"depth_scale" : 999.99993896484375,
> 	"device_name" : "Intel RealSense D415",
> 	"fps" : 30.0,
> 	"height" : 720,
> 	"intrinsic_matrix" : 
> 	[
> 		922.08465576171875,
> 		0.0,
> 		0.0,
> 		0.0,
> 		921.86065673828125,
> 		0.0,
> 		656.0257568359375,
> 		369.18637084960938,
> 		1.0
> 	],
> 	"serial_number" : "024122060367",
> 	"stream_length_usec" : 0,
> 	"width" : 1280
> }
> 
> [Open3D INFO] Capture started with RealSense camera 024122060367
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\defaultLit.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\defaultLitTransparency.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\defaultLitSSR.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\defaultUnlit.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\defaultUnlitTransparency.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\depth.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\unlitGradient.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\normals.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\unlitSolidColor.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\unlitBackground.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\infiniteGroundPlane.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\unlitLine.filamat
> [Open3D DEBUG] LoadMaterialFromFile(): C:\ProgramData\Anaconda3\envs\Open3D\lib\site-packages\open3d\\resources\unlitPolygonOffset.filamat
> [Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
> [Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
> [Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
> [Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
> 
> Restarting kernel...

**Comment by ssheorey** [comment] 2021-07-21 15:55
Thanks @maohong30 can you try this?
Replace line 397-398:
```
self.pcdview.scene.scene.update_geometry('pcd', frame_elements['pcd'],
                                                 update_flags)
```
with these two lines:
```
self.pcdview.scene.scene.remove_geometry('pcd')
self.pcdview.scene.scene.add_geometry('pcd', frame_elements['pcd'], self.pcd_material)
```
Does this avoid the crash?

**Comment by maohong30** [comment] 2021-07-22 12:25
Hi @ssheorey.  After replacing the two lines above. I have the following error.

```
[Open3D INFO] Capture started with RealSense camera 024122060367
[Open3D INFO] Recording [Paused] to bag file 2021-07-22_19-04-41.bag
Traceback (most recent call last):

  File "C:\Users\maoho\Open3D\gui\online-processing.py", line 537, in <module>
    PipelineController(args.camera_config, args.rgbd_video, args.device)
  File "C:\Users\maoho\Open3D\gui\online-processing.py", line 469, in __init__
    gui.Application.instance.run()
  File "C:\Users\maoho\Open3D\gui\online-processing.py", line 479, in <lambda>
    lambda: self.pipeline_view.update(frame_elements))
  File "C:\Users\maoho\Open3D\gui\online-processing.py", line 396, in update
    self.pcdview.scene.scene.remove_geometry('pcd')
AttributeError: 'open3d.cpu.pybind.visualization.rendering.Scene' object has no attribute 'remove_geometry'

```

However, when i replace the two lines with:

```
self.pcdview.scene.remove_geometry('pcd')
self.pcdview.scene.add_geometry('pcd', frame_elements['pcd'], self.pcd_material)
```

the GUI was running fine and more stable. I can even run it in Normals mode. 
I am not sure if this affects the quality of the pointcloud or anything else.  Can that be used as the solution and proceed to Cuda mode? Thanks.

**Comment by ssheorey** [comment] 2021-07-22 16:21
Yes, thanks. The issue is with `update_geometry`. This is a faster path for updating the scene, we'll look into this.
Please let us know how things go with CUDA now.

**Comment by maohong30** [comment] 2021-07-23 11:48
Hi @ssheorey. I reinstalled Open3d from source (with CUDA), and finally the GUI is running fine with CUDA. 
I am able to use the mouse to control the point cloud's view, running in Normals mode and resizing the window without any problem now. Thank you very much for that.

![1](https://user-images.githubusercontent.com/77562730/126775312-3efa1bc8-aaa2-45bb-8b09-210d17a58b07.jpg)


However, now the GUI crashes when I try to show the color and depth video on the `gui.ImageWidget` as shown in the GPU's memory spike above. 

Is this due to the image size difference between `video_size = (240, 320, 3)` and image size of (720 ,1280 ,3) that slowed down the GUI ?

I have problem resizing the image with the format of `Image[size={720,1280}, channels=3, UInt8, CUDA:0]` .

**Comment by maohong30** [comment] 2021-07-25 05:11
Hi @ssheorey .. I managed to fix the gui.ImageWidget crash. The online-processing GUI is working fine now.

First I added the codes below after line 167
 ```
depth_np_cpu = np.array(depth_in_color.cpu())
depth_resized = cv2.resize(depth_np_cpu, dsize=(320,240), interpolation=cv2.INTER_AREA)    
new_depth = o3d.geometry.Image(depth_resized)    
            
color_np_cpu = np.array(self.rgbd_frame.color.cpu())
color_resized = cv2.resize(color_np_cpu, dsize=(320,240), interpolation=cv2.INTER_AREA)                
new_color = o3d.geometry.Image(color_resized)
```

and replaced lines 181-186 with

```
frame_elements = {
    #'color': self.rgbd_frame.color.cpu(),
    'color': new_color,
    #'depth': depth_in_color.cpu(),
    'depth': new_depth,
    'pcd': self.pcd_frame.cpu(),
    'status_message': self.status_message
}
```

http://www.open3d.org/docs/release/python_api/open3d.visualization.gui.ImageWidget.html
`Mostly a convenience function for ui_image.update_image(). If ‘image’ is the same size as the current image, will update the texture with the contents of ‘image’. This is the fastest path for setting an image, and is recommended if you are displaying video. If ‘image’ is a different size, it will allocate a new texture, which is essentially the same as creating a new UIImage and calling SetUIImage(). This is the slow path, and may eventually exhaust internal texture resources.
`


Thank you.

**Comment by ssheorey** [comment] 2021-08-07 22:00
Hi @maohong30 thanks for your help in tracking this down. I've created a PR #3877 to bypass the crash for Windows users. Can you try it out and let me know if it works for you?

**Comment by maohong30** [comment] 2021-09-05 17:20
It is working now. Thank you very much.

**Comment by maohong30** [comment] 2021-09-06 08:59
Hi @ssheorey. Recently I reinstalled Open3d by source to set `USE_SYSTEM_LIBREALSENSE=OFF` because I have problem playing Bag file. Somehow after reinstalling, the GUI has error with the point cloud frame. Previously the GUI was working perfectly.  Please look at the error below. I am not sure what does it mean by **KeyError: ''** Thank you.

```
run online-processing.py --camera-config config/D415.json --device cuda:0
[Open3D DEBUG] RS2_FORMAT_ANY -> ANY
[Open3D DEBUG] RS2_FORMAT_ANY -> ANY
[Open3D DEBUG] RS2_FORMAT_RGB8 -> RGB8
[Open3D DEBUG] RS2_FORMAT_Z16 -> Z16
INFO:root:{
	"color_format" : "RGB8",
	"depth_format" : "Z16",
	"depth_scale" : 999.99993896484375,
	"device_name" : "Intel RealSense D415",
	"fps" : 30.0,
	"height" : 720,
	"intrinsic_matrix" : 
	[
		922.08465576171875,
		0.0,
		0.0,
		0.0,
		921.86065673828125,
		0.0,
		656.0257568359375,
		369.18637084960938,
		1.0
	],
	"serial_number" : "024122060367",
	"stream_length_usec" : 0,
	"width" : 1280
}

[Open3D INFO] Capture started with RealSense camera 024122060367
[Open3D INFO] Recording [Paused] to bag file 2021-09-06_16-42-15.bag
Exception in thread PipelineModel:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Open3D\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\Open3D\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\maoho\Project5\tutorials\Open3D\gui\online-processing.py", line 196, in run
    n_pts += self.pcd_frame.point['points'].shape[0]
KeyError: ''
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.
[Open3D DEBUG] Trying to destroy default resource [Texture, 1, hash: 655361]. Nothing will happen.

```

**Comment by ssheorey** [comment] 2021-09-07 22:39
@maohong30 'points' has been renamed to 'positions' in an API change. Please use the same version for the repo and the Python wheel. (e.g. both master)
Closing this since the original issue has been resolved.

**Closed by ssheorey** 2021-09-07 22:39 UTC
Labels: visualization, Windows
